### ISSUE TITLE
WSL2 support?

### ISSUE THREAD

**Issue by dannyvoid** [DesktopECHO/Pi-Hole-for-WSL1#1]
With WSL2 being public and widely received as of now, has anyone gotten this to work on WSL2?

**Comment by DesktopECHO** [comment]
I haven't tried converting the installation to WSL2 post-setup but I wouldn't bother -- Limitations in WSL2's networking make this more of a hassle than it needs to be.  

Considering WSL1 and WSL2 work perfectly side-by-side, why bother running this in WSL2 when it's a headache to accomplish and there's nothing to gain?
