### ISSUE TITLE
pi.hole does not resolve to admin page

### ISSUE THREAD

**Issue by goodpunk6** [DesktopECHO/Pi-Hole-for-WSL1#10]
With or without a local dns record added to pihole, typing pi.hole in a browser does not bring you to the admin page. 
Not sure how to troubleshoot

**Comment by DesktopECHO** [comment]
Hi there... did you configure the scheduled task to run automatically at start-up?

Did the webpage appear after the install completed?
If so, bookmark the page and use that to access the Pi-hole admin page.

**Comment by goodpunk6** [comment]
> Hi there... did you configure the scheduled task to run automatically at start-up?
> 
> Did the webpage appear after the install completed?
> If so, bookmark the page and use that to access the Pi-hole admin page.

I did configure the schedule task and that runs no problem.
The webpage did not appear until I typed in the hostname and port in a browser. I can reach it via IP and port as well. I just can't get to it via pi.hole

**Comment by DesktopECHO** [comment]
If you open a command prompt and try to ```ping pi.hole``` does it resolve?
What port is the Admin page using, 80 or 60080?

**Comment by goodpunk6** [comment]
It does ping back. admin page is on 60080

**Comment by DesktopECHO** [comment]
Then you would go to:
```http://pi.hole:60080```
Does that work?

**Comment by goodpunk6** [comment]
> http://pi.hole:60080

yes that works

**Comment by DesktopECHO** [comment]
Then you're good to go

**Comment by goodpunk6** [comment]
how can I have it resolve without the port numbers?

**Comment by DesktopECHO** [comment]
Port 80 seems to be in use on your system, which is why 60080 was selected.  You need to free-up that port , then uninstall/reinstall and the installer script will use port 80.
