### ISSUE TITLE
How to undo audit button?

### ISSUE THREAD

**Issue by seanbperiod** [DesktopECHO/Pi-Hole-for-WSL1#103]
Hello 👋

How do I undo the "audit" button? 

I found solutions on reddit, but not sure how to translate these commands for windows or if there is something else I should be doing:

https://www.reddit.com/r/pihole/comments/jfpm0r/pihole_audit_log/

**Comment by DesktopECHO** [comment]
It should be the same.  If you're really stuck, you can backup your config and redeploy.

**Comment by DesktopECHO** [comment]
I may have misunderstood - you're probably looking for how to get to a bash prompt.  Use caution as this logs you in as root:

`C:\Program Files\Pi-hole\LxRunOffline.exe" r -w -n Pi-hole`
