### ISSUE TITLE
No DHCP tab in settings and IPv6

### ISSUE THREAD

**Issue by skinlab** [DesktopECHO/Pi-Hole-for-WSL1#104]
I am trying to enable ipv6 support, and general pi-hole documentation says it should be under settings and then the DHCP tab, but in this build the DHCP tab under settings doesn't exist.

**Comment by DesktopECHO** [comment]
DHCP Server is not supported and is disabled in the Pi-hole Web UI.  
That said, IPv6 should still work out of the box but I have not tested this extensively.

**Comment by skinlab** [comment]
Ok, thanks. Should it be as simple as adding the local host's ipv6 address to pi-hole's DNS upstream servers in the settings? Because as is it doesn't seem like clients using ipv6 are using pi-hole.

**Comment by DesktopECHO** [comment]
Hi... It should just work.  
You can test it by opening a command prompt on the Windows machine running Pi-hole:

`````
C:\>nslookup
Default Server:  xxx.yyy.zzz
Address:  10.74.0.101

> server 127.0.0.1
Default Server:  localhost
Address:  127.0.0.1

> set q=AAAA
> google.com
Server:  localhost
Address:  127.0.0.1

Non-authoritative answer:
Name:    google.com
Addresses:  2607:f8b0:4004:c08::66
            2607:f8b0:4004:c08::65
            2607:f8b0:4004:c08::71
            2607:f8b0:4004:c08::8a
`````

**Comment by Bucking-Horn** [comment]
@skinlab wrote:
>  Because as is it doesn't seem like clients using ipv6 are using pi-hole.

Then your router may be propagating ts own IPv6 address as local DNS server.
This has to be addressed by configuring your router to stop advertising its own IPv6 for DNS (or -if that's not possoible- to advertise your Pi-hole host machine's IPv6 instead).

If your router doesn't support configuring IPv6 DNS, you could consider disabling IPv6 altogether. If your router doesn't support that either, your IPv6-capable clients will always be able to bypass Pi-hole via IPv6.

Consult your router's documentation sources on further details for its IPv6 configuration options.
