### ISSUE TITLE
Stuck on "BITS Transfer" Connecting

### ISSUE THREAD

**Issue by digitalcontemplation** [DesktopECHO/Pi-Hole-for-WSL1#105]
![image](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/assets/97763644/582cedd9-5688-4d3e-981c-1098e13f0f9e)
![image](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/assets/97763644/a6d6dead-1ec3-4cd0-9c1f-0af4229ee668)

It bounces between being primarily the blue highlighted text, and briefly the non- blue highlighted text.

**Comment by barateza** [comment]
This is also happening to me.

**Comment by digitalcontemplation** [comment]
@barateza What was it that you did, so that I could replicate it?

**Comment by barateza** [comment]
@digitalcontemplation that'd be it! Still not sure why BITS wouldn't work - I myself thought that maybe GitHub was soft blocking me - but that doesn't make sense as the link can be downloaded from a browser.

**Comment by DesktopECHO** [comment]
@digitalcontemplation Thanks for the PR.  
Added `$ProgressPreference = 'SilentlyContinue' ` to speed up the download.
