### ISSUE TITLE
how to update?

### ISSUE THREAD

**Issue by lorvent** [DesktopECHO/Pi-Hole-for-WSL1#11]
Hello,

in admin panel, it is showing me that some updates are available.

how can we update to latest version of pihole?

thanks

**Comment by DesktopECHO** [comment]
Don't do this unless you've first made a backup!  Changes upstream may cause trouble in WSL, but at present (Feb 2021) there are no problems and upgrades run smoothly.

- Run the Pi-hole updater:
```"C:\Program Files\Pi-hole\LxRunOffline.exe" r -n Pi-hole -c  "pihole -up"```

- Then install the WSL fix-ups, run:
```"C:\Program Files\Pi-hole\Pi-hole Configuration.cmd"```
- Select "Repair" 

Pi-hole will re-launch with the latest version.

**Comment by lorvent** [comment]
thanks for the help 💯
