### ISSUE TITLE
Could not resolve host/install

### ISSUE THREAD

**Issue by fruitvenison** [DesktopECHO/Pi-Hole-for-WSL1#110]
curl: (6) Could not resolve host: install.Pi-hole.net

update-rc.d: error: unable to read /etc/init.d/pihole-FTL
sed: can't read /var/www/html/admin/settings.php: No such file or directory
sed: can't read /var/www/html/admin/settings.php: No such file or directory
sed: can't read /opt/pihole/piholeDebug.sh: No such file or directory
sed: can't read /opt/pihole/piholeDebug.sh: No such file or directory
/bin/bash: line 1: /etc/dnsmasq.d/05-pihole-custom-cname.conf: No such file or directory
chown: invalid user: ‘pihole:pihole’

Pi-hole Web Admin, /bin/bash: line 1: pihole: command not found

Fails to install. I'm on the latest Windows 11 build and unable to use this.

**Comment by DesktopECHO** [comment]
Open command prompt in Windows.  What's the output from:

`nslookup install.Pi-hole.net 9.9.9.9`

**Comment by fruitvenison** [comment]
nslookup install.Pi-hole.net 9.9.9.9
Server:  UnKnown
Address:  9.9.9.9

*** UnKnown can't find install.Pi-hole.net: Server failed

**Comment by DesktopECHO** [comment]
Do you have restricted internet access?  (Governmental, corporate, or otherwise)

**Comment by fruitvenison** [comment]
Nope, live in the UK. ISP is Virgin Media and I use the ProtonVPN via Split Tunneling for Chrome/Prowlarr for Sonarr purposes. 

If I load install.pi-hole.net on a web browser it redirects to https://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/basic-install.sh

**Comment by DesktopECHO** [comment]
Your computer is unable to use [Quad 9](https://www.quad9.net/) for DNS requests. 
It's probably your VPN causing the issue. 

Uninstall the failed installation:
 `C:\Program Files\Pi-hole\Pi-hole Uninstall.cmd`

Then disconnect from the VPN temporarily and retry the install script.

_Alternatively_, you can edit `PH4WSL1.CMD` and search/replace all occurrances of `9.9.9.9` with a DNS server that works on your network.  You can find which DNS server to use by runnning `ipconfig /all | find "DNS Server"`

**Comment by fruitvenison** [comment]
You are 100% correct.

Disconnected the VPN. Tested. Working.

Stupid, stupid, stupid.

I wrongly assumed split tunneling was working. Obviously not.

Re-trying install now.

Appreciate the help.
