### ISSUE TITLE
Help wanted: Question: what version of Pi-Hole does this deploy?

### ISSUE THREAD

**Issue by BuddhaDiedLaughing** [DesktopECHO/Pi-Hole-for-WSL1#113]
That's it.  Pi-Hole changes seem critical, to me, more often than not.  Several have come out since this project was last modified.  I'm not smart enough to determine if it's coded such that it downloads the current release of RPiH, or not.  I'd appreciate a hint.  

Either way, thank you for this one of a kind solution to something to help we multitudes of folks who value control but lack the time, energy, resources and/or raw talent to do much more than make a mess of it.  Pi -Hole is such an exemplary project & very popular.  With your simplified setup combined with a stretch of more or less thankless, routine maintenance to accommodate new releases I imagine like this  this project could eventually be responsible for so many new active instances as to dwarf the current numbers.

Never quit!

**Comment by DesktopECHO** [comment]
Thanks for the kind words!

The script installs the latest version of Pi-hole.  
When upstream creates a new release you only need to run the update script:

`C:\Program Files\Pi-hole\Pi-hole System Update.cmd`
