### ISSUE TITLE
Pi-hole WSL folder not accessible from Windows anymore

### ISSUE THREAD

**Issue by mauripop** [DesktopECHO/Pi-Hole-for-WSL1#114]
I had been using Pihole as installed by this script for a couple of years. After a reboot recently, the WSL folder for Pihole stopped being accessible. 

On File Explorer, I see the "Pi-hole" folder, but when I try to open it, this is displayed:

`\\wsl.localhost\Pi-hole is not accessible. You might not yet have permission to use this network resource....`

I uninstalled Pihole using the CMD file in the Program Files Folder. I also removed the WSL folder from the command line, and then I tried a fresh install using the latest version of the script. 

When running the installation script, I see the following errors right after "Please wait a few minutes for package installer...":

```
Error: 0xd000020c
Error code: Wsl/Service/CreateInstance/0xd000020c
Error: 0xd000020c
Error code: Wsl/Service/CreateInstance/0xd000020c
Error: 0xd000020c
Error code: Wsl/Service/CreateInstance/0xd000020c
Update setupVars.conf to use IP address  on interface  . . .
Error: 0xd000020c
Error code: Wsl/Service/CreateInstance/0xd000020c
Error: 0xd000020c
Error code: Wsl/Service/CreateInstance/0xd000020c
Error: 0xd000020c
Error code: Wsl/Service/CreateInstance/0xd000020c
Error: 0xd000020c
Error code: Wsl/Service/CreateInstance/0xd000020c
```

I see the Pi-hole folder created again on File Explorer, but it's still not accessible. Same error. 

I enclose the log files from the "c:\programfiles\pi-hole"  folder. 

[Interface.txt](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/files/14580323/Interface.txt)
[IP.txt](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/files/14580324/IP.txt)
[Pi-hole install settings.log](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/files/14580325/Pi-hole.install.settings.log)
[Pi-hole package install.log](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/files/14580326/Pi-hole.package.install.log)

**Comment by DesktopECHO** [comment]
Hello, this is a bug in WSL - updating to 2.1.5 should sort you out.
https://github.com/microsoft/WSL/issues/11255#issuecomment-1989894835

**Comment by mauripop** [comment]
Yes, updating to WSL 2.1.5.0 fixed this. Thanks!
