### ISSUE TITLE
Automatic task start fails

### ISSUE THREAD

**Issue by WillScarlettOhara** [DesktopECHO/Pi-Hole-for-WSL1#117]
Hi,

I can't make it work. Error code 2147943726. It seems to be a authentification problem. I use an online Microsoft account to login.

![image](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/assets/39462014/b793aae1-9662-4083-87be-921f2788b2fa)
![image](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/assets/39462014/13f2e686-f3e9-43c5-be62-dd725dd6d17b)

I tried to change user with my Microsoft account credentials but I can't.
![image](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/assets/39462014/96203579-e98e-4277-ab32-53c3de6652c7)
![image](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/assets/39462014/abf2dbb2-89bd-4055-a643-18ebff2b0114)

The problem can be quickly fixed with a shortcut in the start menu for a pi-hole startup after login. The problem is that I'm letting a bit of tracking through at each startup. Though, I use a Microsoft account to connect to Windows, so there's no point in fighting Microsoft's tracking, I guess.

For info, I use 2FA and a Windows Hello PIN but I have disabled the credentials request at startup.

Thanks

**Comment by DesktopECHO** [comment]
You may want to create a local/service account on your machine and install Pi-hole under that account.  
Then you can set that account to launch the Pi-hole scheduled task at system start-up.

> The problem is that I'm letting a bit of tracking through at each startup.

This shouldn't happen if Pi-hole is your only DNS server, the lookups should fail.
If you have other DNS servers defined then you will still see ads intermittently.

**Comment by DesktopECHO** [comment]
>Another topic but what preferred DNS server should I use in IPv4 windows network properties?

In this situation, Pi-hole is running locally on the same device so IPv4 localhost (127.0.0.1) will work.

**Comment by WillScarlettOhara** [comment]
Thanks

**Comment by alainbryden** [comment]
For what it's worth - I experienced the automatic task start failure as well.

I followed instructions to set to "Run whether user is logged in or not" and the scheduled task wouldn't get run at startup.

Anecdotally, I got it working by just reverting to the default setting "Run only when user is logged on"

There are similar reported problems floating around, not sure if related:
- https://github.com/microsoft/WSL/issues/8835
- https://answers.microsoft.com/en-us/windows/forum/all/windows-11-22h2-upgrade-breaks-run-whether-user-is/3469fd3d-9b89-4d66-b523-501baf57185e
- https://superuser.com/questions/1334931/task-scheduler-batch-run-whether-user-is-logged-on-or-not-not-working?rq=1
