### ISSUE TITLE
Maximum number of concurrent DNS queries reached

### ISSUE THREAD

**Issue by rsunny2012** [DesktopECHO/Pi-Hole-for-WSL1#118]
Hello,

i am getting the below error frequently

Maximum number of concurrent DNS queries reached

DNSMASQ_WARN Warning in `dnsmasq` core:
Maximum number of concurrent DNS queries reached (max: 150)

I am trying to follow the below guide to fix the issue

https://discourse.pi-hole.net/t/resolved-maximum-number-of-concurrent-dns-queries-reached/60970/2

when i added  02-custom-settings.conf file under /etc , after reboot its giving me message that permission denied and pihole never start

is there something i am doing wrong or what is the best way to fix the above error

**Comment by DesktopECHO** [comment]
> when i added 02-custom-settings.conf file under /etc

What are the steps you took to change this file?  Reason I ask is that you can't do this directly from Windows Explorer, you need to jump into the Linux instance first `wsl -d Pi-hole` and edit the file from there.

**Comment by rsunny2012** [comment]
can you give the exact command to edit the file. 
i have edited the file directly on windows and it did not worked as you have mentioned

**Comment by DesktopECHO** [comment]
The instructions are the same as the link you provided, except for the first step: `Connect to pihole via SSH`.   Instead of connecting via SSH, open a command prompt and run this command instead `wsl -d Pi-hole`

Then you can run `sudo nano /etc/dnsmasq.d/02-custom-settings.conf` and create the new configuration file.

**Comment by rsunny2012** [comment]
Thank you. I have made the change. you can close the conversation
