### ISSUE TITLE
lighttpd 500 Internal Server Error

### ISSUE THREAD

**Issue by alainbryden** [DesktopECHO/Pi-Hole-for-WSL1#119]
I'm currently troubleshooting an occasional error, where I'll try to log into the pi-hole dashboard and get a 500 Internal Server Error. Refreshed and got the same error, but manually re-running the "pi-hole launcher" script fixed things again.

I dug out the `var\log\lighttpd\error-pihole.log` and it read:

```
2024-05-25 14:21:52: server.c.1513) server started (lighttpd/1.4.59)
2024-05-25 16:46:43: mod_fastcgi.c.419) unexpected end-of-file (perhaps the fastcgi process died):pid: 93 socket: unix:/run/lighttpd/pihole-php-fastcgi.socket-0
2024-05-25 16:46:43: gw_backend.c.2275) response not received, request sent: 1007 on socket: unix:/run/lighttpd/pihole-php-fastcgi.socket-0 for /admin/index.php?, closing connection
2024-05-25 16:46:46: mod_fastcgi.c.419) unexpected end-of-file (perhaps the fastcgi process died):pid: 93 socket: unix:/run/lighttpd/pihole-php-fastcgi.socket-0
2024-05-25 16:46:46: gw_backend.c.2275) response not received, request sent: 1030 on socket: unix:/run/lighttpd/pihole-php-fastcgi.socket-0 for /admin/index.php?, closing connection
2024-05-25 16:49:22: server.c.1513) server started (lighttpd/1.4.59)
```

I tried digging into the error message "perhaps the fastcgi process died", but didn't get far. Prior to this I was running `pihole/pihole:latest` in docker for a couple years, so I'm loosely familiar with pihole, lighttpd and dnsmasq.d - less so with any of the other processes involved. I'm not finding any logs for fastcgi.

I'm using WSL 1 on Windows 10 22H2.  My dockerized instance had good uptime, but it's a memory hog so I'm hoping I can get this working insteaed. I've read about some issues with WSL just [locking up](https://superuser.com/questions/1713488/wsl-stops-responding) sometimes, hopfully it's nothing like that.

**Comment by DesktopECHO** [comment]
This is a new one; I haven't seen this error show up over the four-ish years the script has been around.
  
What antivirus software are you using?  You may need to add an exclusion for folder:
`C:\Program Files\Pi-hole\rootfs\run\lighttpd`

Have you tried re-deploying a new instance, if so do the errors persist?

FYI availability isn't normally a problem - I have WSL1 instances of Pi-hole running months at a time without issue.  It would go longer if I didn't need to reboot occasionally for Windows Update.

**Comment by alainbryden** [comment]
Just windows defender in place, and nothing seems to be blocked at the offset, it just appears to do this after a few hours idle. I 

I'm working my way through a few theories. Each of the 4 times it's happened so far it's been after I've leaft my pihole alone for a couple hours. I'm thinking a long time ago I might have tweaked WSL in some way that puts processes to sleep if they don't do anything for a while. I don't think it's anything in my .wslconfig though, which is:

```
[wsl2]
memory=512MB
processors=4
swap=8GB
swapFile=c:\\wslswapfile.vhdx

# [experimental]
# autoMemoryReclaim=gradual
# sparseVhd=true
```

Last night I set up Firefox to auto-refresh the pihole admin page every 60 seconds, and everything is still up and running fine. Next I'm going to close down the page and see if it dies again later this evening. If so, it must be some sort of setting that kills idle processes.

I'll add a from-scratch install to my list of things to try after that.

**Comment by alainbryden** [comment]
Small update: I tried updating WSL, but it was already at the latest. I stopped polling the UI and left my computer idle for a few hours, but haven't reproduced the issue a 5th time yet. I don't think I've changed anything that would have fixed it yet (other than restarting my PC a few times).

When I first saw the error log and the message "perhaps the fastcgi process died" I didn't see anything with that name. I didn't realize that the "fastcgi" process it was referring to was named "php-cgi" - so I'm hoping to reproduce the error once more and launch `top` so I can see whether it was in fact dead or not. So far any time I've checked, it's been up and running (with 4 child processes, as configured).

Let's close this as cannot reproduce for now (since you have such a clean backlog) and I will poke back if I am able to narrow down the root cause and/or any action I manage to take that makes the problem go away.

**Comment by MaddineniManohar** [comment]
I'm having a similar issue. It worked fine after install. Getting 500 errors after trying to update via powershell. I used "wsl pihole -up"

**Comment by alainbryden** [comment]
An update, it's been a couple months, and every few days I start getting fastcgi errors of one kind or another. I've set up a scheduled task to re-run `Pi-hole Launcher.cmd` at 7am every day, but even then I still catch it failing mid-day and have to manually reboot things.

An exerpt of some of the different errors seen in the `lighttpd\error-pihole.log`:

"Call to undefined function enable()" - there are hundreds of these
```
2024-07-09 07:00:03: mod_fastcgi.c.487) FastCGI-stderr:PHP Fatal error:  Uncaught Error: Call to undefined function enable() in /var/www/html/admin/api.php:15
2024-07-09 07:00:03: mod_fastcgi.c.487) FastCGI-stderr:Stack trace:
2024-07-09 07:00:03: mod_fastcgi.c.487) FastCGI-stderr:#0 {main}
2024-07-09 07:00:03: mod_fastcgi.c.487) FastCGI-stderr:  thrown in /var/www/html/admin/api.php on line 15
```

"unexpected end-of-file (perhaps the fastcgi process died)" - as originally reported. Also happens frequently, but not even as frequently as the above error. This comes in two flavours:
1. "response not received"
```
2024-07-09 08:48:04: mod_fastcgi.c.419) unexpected end-of-file (perhaps the fastcgi process died):pid: 93 socket: unix:/run/lighttpd/pihole-php-fastcgi.socket-0
2024-07-09 08:48:04: gw_backend.c.2275) response not received, request sent: 894 on socket: unix:/run/lighttpd/pihole-php-fastcgi.socket-0 for /admin/api.php?getQueryTypes, closing connection
```

2. "response already sent out, but backend returned error on socket"
```
2024-07-09 08:49:04: gw_backend.c.2281) response already sent out, but backend returned error on socket: unix:/run/lighttpd/pihole-php-fastcgi.socket-0 for /admin/index.php?, terminating connection
2024-07-09 08:49:05: mod_fastcgi.c.419) unexpected end-of-file (perhaps the fastcgi process died):pid: 93 socket: unix:/run/lighttpd/pihole-php-fastcgi.socket-0
```

**Comment by DesktopECHO** [comment]
> I'm having a similar issue. It worked fine after install. Getting 500 errors after trying to update via powershell. I used "wsl pihole -up"

@MaddineniManohar - You should update by running `Pi-hole System Update.cmd` in `C:\Program Files\Pi-hole`

@alainbryden - I spun-up a couple of test instances to try and re-create this issue.  Did your issues appear soon after re-installing or did they show up later on?

**Comment by alainbryden** [comment]
The issues I'm experiencing are pretty sporadic. They also don't affect
core dns capabilities, only the ability to load up the pihole admin
dashboard. I only notice because I tend to leave the admin page up on a
screen 24/7, and once every few days I'll see that it's been hung for a
while, then go check the logs, run the launch script, and it's typically
fine for a few more days.

I've read a few reports of wsl sockets timing out and causing general grief
with fast_cgi over the past 5 years, so I doubt it's even anything we can
control, perhaps just a problem that manifests itself based on my usage
patterns.

**Comment by DesktopECHO** [comment]
I'm not able to reproduce, but try adding this to your `/etc/lighttpd/lighttpd.comf`:

`server.stream-request-body = 1` 
 (Try `2` as well)

Or if you're feeling adventurous, you can uninstall and try the v6 beta which does not use PHP at all:
`https://github.com/DesktopECHO/Pi-Hole-for-WSL1/raw/v6/PH4WSL1.cmd`

**Comment by alainbryden** [comment]
It's been weeks since my last from scratch install and the problem has
vanished.

Perhaps when  I did my last installs, the latest pinhole/ftl available had
an issue that is now resolved, or I botched it some other way.

So for anyone else with this issue, try nuking it and starting over again.
