### ISSUE TITLE
Broken after system restore/restore point

### ISSUE THREAD

**Issue by imp69** [DesktopECHO/Pi-Hole-for-WSL1#120]
So I had a totally unrelated issue that I had to use a restore point for. Afterwords, the pi-hole refused to launch. Tried to manually get it to start, but no processes related to it ran.  So I figured I'd just use the uninstall batch to reinstall it and successfully uninstalled it.  Now I have the issue of it simply not installing. 

![cmd_2024-06-03_04-19-21](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/assets/100172758/e9d00610-02ba-42ae-8caf-cdf1f8aa11d7)
What I get is that. I have checked everywhere for any leftovers and I can't find any at all.  Any idea how I might go about fixing this? I can't provide logs because it doesn't even make the folder, and it's ran as admin/seemingly proper permissions.

**Comment by imp69** [comment]
This can be closed now, I fixed it by redownloading WSL via the repo. Docker failed to work, so I figured it was WSL, and it didn't matter how many times I disabled/re-enabled WSL, WSL failed to work. So if anyone else ends up encountering this particular problem you should try doing that; https://github.com/microsoft/WSL/releases?page=1

Thank you for the script by the way! Makes it very simple when Windows isn't being a monster!

**Comment by DesktopECHO** [comment]
Thanks!   Glad to hear you have it sorted.
