### ISSUE TITLE
Pi breaks down after every restart

### ISSUE THREAD

**Issue by antebudimir** [DesktopECHO/Pi-Hole-for-WSL1#13]
Hi! Happy to see Pi-Hole on Windows. Straightforward setup, easy to use.

So, installation goes exactly as described. Pi-Hole admin tab pops up and everything's working fine. Then after the first restart, it stops working. Admin tab can't be opened and I have to run Pi-hole Configuration.cmd. Repair. It repairs it in 30 seconds, Pi-Hole admin tab pops up again and everything's ok. Until the next restart...

While it's working cron & atd processes are using 14% of CPU each. That seems pretty high to me.
My setup is: WIN10 Pro, Ver. 1903, Build 18362.836.
Machine: Intel Core i7-9750H CPU @ 2.60GHz (6 cores), 16Gb RAM

**Comment by DesktopECHO** [comment]
Hi Ante, did you set up the scheduled task per the readme file?

Includes a Scheduled Task to accommodate auto-start at boot, before logon.

Configure this by opening Windows Task Scheduler (taskschd.msc) and right-click the **Pi-hole for Windows** task, click **edit.**
On the **General** tab, place a checkmark next to both **Run whether user is logged on or not** and **Hidden**
On the **Conditions** tab, un-check the option **Start the task only if the computer is on AC power**

**Comment by antebudimir** [comment]
Yes, the scheduled task does indeed sort the restart problem and now Pi starts as expected after restart. 
But the CPU usage perseveres at 27% (cron & atd 13% each) whereas when idle without Pi my PC is at 1% CPU usage.
That seems a bit high to me. Is that expected or?

**Comment by DesktopECHO** [comment]
Hi, what version of Windows are you running?  If you're not up to date you may be running into the sleep bug fixed last September.  This issue is fixed in 20H2 and there are updates for older builds available on Windows Update.

**Comment by antebudimir** [comment]
Here's the info:
Edition: Windows 10 Pro
Version: 20H2
Installed on: 28-‎Mar-‎21
OS build: 19042.870
Experience: Windows Feature Experience Pack 120.2212.551.0

After reinstalling everything yesterday, now I get the following error (screenshot attached). Tried it a couple of times but it won't install properly.
![Install](https://user-images.githubusercontent.com/57053530/112835079-16180100-9099-11eb-8782-8e23b2b5d702.jpg)

**Comment by DesktopECHO** [comment]
Are the DNS settings correct on your local machine now that Pi-hole is uninstalled?  Everybody does this at least once :)

**Comment by antebudimir** [comment]
Back to square one. :D
Installed it successfully, edited task scheduler but it simply won't start on its own nor manually. Pi-hole Launcher.cmd doesn't do anything. To launch it, I have to go through Pi-hole Configuration.cmd. I select repair, then it goes through some half installation process and it starts successfully. After restart, the same thing.

**Comment by DesktopECHO** [comment]
Run the uninstaller script, reboot, re-install.   
If that doesn't work try with a different user profile.
