### ISSUE TITLE
Antivirus struggles

### ISSUE THREAD

**Issue by rausb** [DesktopECHO/Pi-Hole-for-WSL1#14]
Hi,

thanks for your work, this script really helped a lot.

My Bitdefender anti-virus stopped the script half way for "suspicious behaviour" before the uninstall script was installedl. This led to a bit of work to manually revert to the original state, because simply using the install skript would cause it to immediately crash.

If you could add a warning to maybe deactivate anti-virus beforehand, that'd be great.

Thanks again, and keep it up
greetings

**Comment by DesktopECHO** [comment]
Hi there thanks for your feedback.  I will link to this issue and try to integrate it into the documentation.
