### ISSUE TITLE
question - how do i use DNSCrypt instead of CloudflareDNS

### ISSUE THREAD

**Issue by VPraharsha03** [DesktopECHO/Pi-Hole-for-WSL1#16]
Right now i'm running DNSCrypt which runs as a windows service on port 53. How can i make it run as a service on startup on linux side (WSL) ? Want some help writing the configuration. Or instead can the existing Windows service be used along with Pi-Hole ?

**Comment by DesktopECHO** [comment]
Hi... if you look in [DNS settings ](http://localhost/admin/settings.php?tab=dns)you will see the entry ``127.0.0.1#5053``

This means Pi-hole uses DNS server on port 5053 (cloudflared) for lookups.

Change this to whatever port DNScrypt/etc... answers on.  Make sure it's NOT port 53, Pi-hole uses that!

I have tested [dnscrypt-windows](https://www.dnscrypt.org/#dnscrypt-windows) - It can run as a service, and runs fine with Pi-hole, just remember to set the port to something other than 53.

**Comment by VPraharsha03** [comment]
> Change this to whatever port DNScrypt/etc answers on. Make sure it's NOT port 53, Pi-hole uses that!

I've tried changing the port of dnscrypt-proxy and it doesn't work on any port other than 53

**Comment by VPraharsha03** [comment]
I've tried changing the port of DNSCrypt and it works. But i get a ``[✗] DNS service is NOT listening`` error on running Update Gravity

**Comment by DesktopECHO** [comment]
That should only be cosmetic, does it still work otherwise?

Run “Pi-hole Configuration.cmd" and select repair after updating Pi-hole.  Should indicate all ok after that.

**Comment by DesktopECHO** [comment]
The notification ```[✗] DNS service is NOT listening``` at the bottom is ok to ignore for now, this is a cosmetic issue but needs to be corrected:

![image](https://user-images.githubusercontent.com/33142753/120073072-364e4700-c06d-11eb-9a54-b2106f0da1f2.png)

Al long as you see Status as ACTIVE in the Web UI, you know Pi-hole is running ok:
![image](https://user-images.githubusercontent.com/33142753/120073178-ab218100-c06d-11eb-898d-97bd69353887.png)

For example, if you kill pihole-FTL in the Task Manager and reload the Admin page you'll see it reports as down:
![image](https://user-images.githubusercontent.com/33142753/120073424-985b7c00-c06e-11eb-804c-fcaaa47ea08f.png)
(If you do this little experiment, click "Restart DNS resolver" in Settings to bring it back up.)

**Comment by VPraharsha03** [comment]
Thanks for the clarification, much appreciated. And, yes PiHole is up and blocking sites, DNSCrypt is working fine too.

**Comment by DesktopECHO** [comment]
> I've tried changing the port of DNSCrypt and it works. But i get a `[✗] DNS service is NOT listening` error on running Update Gravity

This has been resolved in the latest commit.

**Comment by Kncuk** [comment]
Hi, I also want to ask about DNScrypt with Pi-hole, if I understand correctly I need to set the port DNScrypt is listening to to something other than 53 (say 2345 etc)? and set the one in Pi-Hole to that port as well?
