### ISSUE TITLE
Can I change the default port 80? 

### ISSUE THREAD

**Issue by 9xcoder** [DesktopECHO/Pi-Hole-for-WSL1#17]
I used port 80 for web server
Could you provide a solution to change default port ? 
Sorry for my bad English

**Comment by DesktopECHO** [comment]
Hello, the script tries to detect if something is already listening on port 80.  
If there is, it will set the web admin port to 60080 to avoid a conflict.

To force a specific port number, change line 8 from:
````IF %SIZE% gtr 0 SET PORT=60080````
to:
````SET PORT=8080````
...and the script will use port 8080 for Pi-hole web admin.
