### ISSUE TITLE
using wsl2 "/etc/resolv.conf" does not get generated under hyper-v with multiple interfaces

### ISSUE THREAD

**Issue by TheBigBear** [DesktopECHO/Pi-Hole-for-WSL1#18]
I found that it installs well on any win 10 PC where hyper-v is not active. But it does not work on a Hyper-v server or when win 10 pro has hyper-v active. 
My assumption it has to do with the way wsl 2 starts up with hyper-v present. 

This is the output:

```
--------------------------------
 Pi-hole for Windows v.20210522
--------------------------------

Set location for 'Pi-hole' install folder or hit enter for default [C:\Program Files] ->

Pi-hole will be installed in "C:\Program Files\Pi-hole" and Web Admin will listen on port 60080
Press any key to continue . . .

This will take a few minutes to complete...
Installing LXrunOffline.exe and Debian -> Compacting the install
W: Failed to fetch http://deb.debian.org/debian/dists/buster/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/buster-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/buster/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://ftp.debian.org/debian/dists/buster-backports/InRelease  Temporary failure resolving 'ftp.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
-> Install dependencies
E: Unable to locate package gpg
E: Unable to locate package wget
E: Unable to locate package curl
E: Package 'ca-certificates' has no installation candidate
E: Unable to locate package libpcre2-8-0
E: Unable to locate package libpsl5
E: Unable to locate package openssl
E: Unable to locate package perl-modules-5.28
E: Couldn't find any package by glob 'perl-modules-5.28'
E: Couldn't find any package by regex 'perl-modules-5.28'
E: Unable to locate package libgdbm6
E: Unable to locate package libgdbm-compat4
E: Unable to locate package libperl5.28
E: Couldn't find any package by glob 'libperl5.28'
E: Couldn't find any package by regex 'libperl5.28'
E: Package 'perl' has no installation candidate
E: Unable to locate package libcurl3-gnutls
E: Unable to locate package liberror-perl
E: Unable to locate package git
E: Unable to locate package lsof
E: Unable to locate package unattended-upgrades
E: Package 'anacron' has no installation candidate
E: Unable to locate package inetutils-syslogd
E: Unable to locate package dns-root-data
E: Unable to locate package dnsutils
E: Unable to locate package gamin
E: Unable to locate package idn2
E: Unable to locate package libgamin0
E: Package 'lighttpd' has no installation candidate
E: Unable to locate package netcat
E: Unable to locate package php-cgi
E: Unable to locate package php-common
E: Unable to locate package php-intl
E: Unable to locate package php-sqlite3
E: Unable to locate package php-xml
E: Unable to locate package php7.3-cgi
E: Couldn't find any package by glob 'php7.3-cgi'
E: Couldn't find any package by regex 'php7.3-cgi'
E: Unable to locate package php7.3-cli
E: Couldn't find any package by glob 'php7.3-cli'
E: Couldn't find any package by regex 'php7.3-cli'
E: Unable to locate package php7.3-common
E: Couldn't find any package by glob 'php7.3-common'
E: Couldn't find any package by regex 'php7.3-common'
E: Unable to locate package php7.3-intl
E: Couldn't find any package by glob 'php7.3-intl'
E: Couldn't find any package by regex 'php7.3-intl'
E: Unable to locate package php7.3-json
E: Couldn't find any package by glob 'php7.3-json'
E: Couldn't find any package by regex 'php7.3-json'
E: Unable to locate package php7.3-opcache
E: Couldn't find any package by glob 'php7.3-opcache'
E: Couldn't find any package by regex 'php7.3-opcache'
E: Unable to locate package php7.3-readline
E: Couldn't find any package by glob 'php7.3-readline'
E: Couldn't find any package by regex 'php7.3-readline'
E: Unable to locate package php7.3-sqlite3
E: Couldn't find any package by glob 'php7.3-sqlite3'
E: Couldn't find any package by regex 'php7.3-sqlite3'
E: Unable to locate package php7.3-xml
E: Couldn't find any package by glob 'php7.3-xml'
E: Couldn't find any package by regex 'php7.3-xml'
E: Unable to locate package sqlite3
E: Unable to locate package unzip
E: Unable to locate package dhcpcd5
/bin/bash: wget: command not found
/bin/bash: wget: command not found
dpkg: error: cannot access archive './cloudflared-stable-linux-amd64.deb': No such file or directory
chmod: cannot access 'cloudflared': No such file or directory
mv: cannot stat 'cloudflared': No such file or directory
update-rc.d: error: unable to read /etc/init.d/cloudflared
/bin/bash: gpg: command not found
Usage: useradd [options] LOGIN
       useradd -D
       useradd -D [options]

Options:
  -b, --base-dir BASE_DIR       base directory for the home directory of the
                                new account
  -c, --comment COMMENT         GECOS field of the new account
  -d, --home-dir HOME_DIR       home directory of the new account
  -D, --defaults                print or change default useradd configuration
  -e, --expiredate EXPIRE_DATE  expiration date of the new account
  -f, --inactive INACTIVE       password inactivity period of the new account
  -g, --gid GROUP               name or ID of the primary group of the new
                                account
  -G, --groups GROUPS           list of supplementary groups of the new
                                account
  -h, --help                    display this help message and exit
  -k, --skel SKEL_DIR           use this alternative skeleton directory
  -K, --key KEY=VALUE           override /etc/login.defs defaults
  -l, --no-log-init             do not add the user to the lastlog and
                                faillog databases
  -m, --create-home             create the user's home directory
  -M, --no-create-home          do not create the user's home directory
  -N, --no-user-group           do not create a group with the same name as
                                the user
  -o, --non-unique              allow to create users with duplicate
                                (non-unique) UID
  -p, --password PASSWORD       encrypted password of the new account
  -r, --system                  create a system account
  -R, --root CHROOT_DIR         directory to chroot into
  -s, --shell SHELL             login shell of the new account
  -u, --uid UID                 user ID of the new account
  -U, --user-group              create a group with the same name as the user
  -Z, --selinux-user SEUSER     use a specific SEUSER for the SELinux user mapping


Launching Pi-hole installer...

/bin/bash: curl: command not found
sed: can't read /var/www/html/admin/settings.php: No such file or directory
sed: can't read /var/www/html/admin/settings.php: No such file or directory
sed: can't read /var/www/html/admin/scripts/pi-hole/php/header.php: No such file or directory
sed: can't read /var/www/html/admin/scripts/pi-hole/php/header.php: No such file or directory
sed: can't read /etc/lighttpd/lighttpd.conf: No such file or directory
sed: can't read /opt/pihole/piholeDebug.sh: No such file or directory
sed: can't read /opt/pihole/piholeDebug.sh: No such file or directory
sed: can't read /usr/local/bin/pihole: No such file or directory
sed: can't read /usr/local/bin/pihole: No such file or directory
sed: can't read /usr/local/bin/pihole: No such file or directory
sed: can't read /usr/local/bin/pihole: No such file or directory
sed: can't read /usr/local/bin/pihole: No such file or directory
sed: can't read /usr/local/bin/pihole: No such file or directory
/bin/bash: pihole: command not found
chown: invalid user: ‘pihole:pihole’
chown: invalid user: ‘pihole:pihole’
/bin/bash: pihole: command not found

--------------------------------------------------------------------------------
Pi-hole Web Admin, /bin/bash: pihole: command not found
--------------------------------------------------------------------------------
SUCCESS: The scheduled task "Pi-hole for Windows" has successfully been created.

Pi-hole for Windows installed in C:\Program Files\Pi-hole
Press any key to continue . . .

C:\Program Files>
```

If I run bash I see that the /etc/resolv.conf as originally shipped  is still in place and has not been adjusted by the wsl 2 startup as it should have been.

```
PS C:\Program Files\Pi-hole>lxrunoffline r -n Pi-Hole
root@WIN:/mnt/c/Program Files\Pi-hole# ping -c 1 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=58 time=17.9 ms

--- 1.1.1.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 17.857/17.857/17.857/0.000 ms
root@WIN:/mnt/c/Program Files\Pi-hole# ping -c 1 www.google.com
ping: www.google.com: Temporary failure in name resolution
root@WIN:/mnt/c/Program Files\Pi-hole# cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 192.168.108.1
root@WIN:/mnt/c/Program Files\Pi-hole# 
```

**Comment by DesktopECHO** [comment]
Hi there... I'm curious why would you want to run Pi-hole in WSL2?   Do you have a use-case where it's needed?
I've found netowrking in WSL2 to be troublesome at times, and it has a bigger overhead than WSL1.
Thanks,
D.

**Comment by TheBigBear** [comment]
HI 

I am not running it in WSL2 . But the windows server has been updated to be wsl2 compatible. ( both on hyper-v 2019 and hyper-v 2022 as well as win 10 pro with hyper-v )

And on all those your installer ( even though it installs itself as WSL 1 ) does not create a working /etc/resolv.conf .

Maybe I should have left off mentioning wsl2 , but I assumed that your software has been tested and worked well under wsl 1 systems, 

But I only just started under machines that are wsl2 updated and on those the DNS Resolver does not work as I have shown, and if I remove the existing original etc/resolv.conf and then restart the networking service the installer finishes fine.

Does that help and make sense? Or are you left with any more questions ? 

Thanks for having written this.

Regards,

Urs 

PS: My main usage is to use your pi hole for wsl 1 on our hyper-v  servers. But I have not mid or long term experience with this setup. It seems to fail on the install not having DNS Resolver. Are you saying that the plan to using pi hole for wsl 1 is not stable enough to use because of networking issues?

**Comment by DesktopECHO** [comment]
Look similar to this mess?
https://github.com/microsoft/WSL/issues/4285

I commited a change to work around this issue, let me know if it works for you.

To answer your other question -- Under WSL1, I consistently get 90+ days Pi-hole uptime, It Just Works every time.  That's the longest I can go without needing to reboot for security updates.  I've found it quite reliable and light on resource utilization.
Thanks,
D.

**Comment by TheBigBear** [comment]
Almost looks to me as if we have to write a bash function to check dns resolution and if not reset networking and re-test until it works and call it the three or four times before we fetch stuff of the net?

**Comment by DesktopECHO** [comment]
Fixed it on one server, that's strange.
When you launch the install, are you sure the Windows host has DNS is configured to point at a live DNS server?

**Comment by TheBigBear** [comment]
Yes, that was/is the first thing I check. after my much shorter PR and only doing it once it then had a 'proper' resolv.conf that showed me not only the nameserver but also correct search domain etc. But I am fine forcing dns resolution over Cloudflare .

**Comment by TheBigBear** [comment]
and once the wsl instance is created I can even connect another console with 'LxRunOffline r -n Pi-Hole' and then test  dns resolution and internet reachability and it keeps falling back to the ```Temporary failure resolving``` warning at different times during the install phase..

**Comment by DesktopECHO** [comment]
In addition to having the installer behave the same on different versions of Windows, I'm also trying to assure Pi-hole can update when the host's DNS is set to 127.0.0.1... which now works using the latest commit on Server Core and Win10 21H2 when the host DNS is changed to 127.0.0.1

The problem is also a behaviour change in WSL on Windows 1803/9 and 1909.  
Each time ```WSL.EXE -d Pi-hole``` is run, WSL overwrites /etc/resolv.conf
I don't think 1809 recognises generateResolvConf=false
It instead uses the following line in /etc/resolv.conf to control how DNS is set up.
```# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line```

If you get a DNS error when the script runs this command you may have an issue elsewhere.  It doesn't make sense my commit would only resolve the issue only one of the machines. 
 
```echo 'nameserver 1.1.1.1' > /etc/resolv.conf ; pihole -r```
 In WSL#4285 people have reported uninstalling/reinstalling the roles can clears this up.

Do you have antivirus/defender enabled?

**Comment by DesktopECHO** [comment]
One more thing to try, no idea if it will help -- Instead of ```nameserver 1.1.1.1``` try using ```nameserver 8.8.8.8``` 

I don't think ```service networing restart``` does anything in WSL1.   For example I can run ```service networing stop``` and still ping/wget in WSL1 without issue.
Core networking is a part of Windows in WSL1 (In WSL2 it's paravirtualized)

**Comment by TheBigBear** [comment]
OK. It now also installed on those other two. ;-) I had a hint you didn't know. ;-) They are in a restrictive network where egress is not slowing everything so a number of installer script actions where being blocked by the local network there. including the dig call to versions.pi-hole.net ( external DNS access is a NO NO in many networks. But even some of the other internet accesses had been blocked. Thanks for the stabilising of this under windows core.

**Comment by DesktopECHO** [comment]
Excellent news!  Glad to hear you have it sorted out.
