### ISSUE TITLE
Readme ends abruptly

### ISSUE THREAD

**Issue by kevinlinxc** [DesktopECHO/Pi-Hole-for-WSL1#20]
Hi, what do you do after running the executable? I assume you proceed with installation normally, but I'm not sure what that is because this is my first exposure to Pi-Hole. Maybe a link to another setup guide would be good

**Comment by DesktopECHO** [comment]
When the instaler completes, a browser window should open the Pi-hole web interface.   
That means it's ready to use -- make sure you setup the scheduled task to launch Pi-hole at boot (per the readme)

If Pi-hole is running and you verified it starts-up at boot, you just set the DNS to point at the IP of your machine.  That's all, you're up and running.

**Comment by DesktopECHO** [comment]
Hi there, I updated README.md with a link to an installation walk-thru on YouTube.  Hopefully that will clear up any confusion for people new to Pi-hole.
