### ISSUE TITLE
Unable to determine if the detected OS (Debian 10) is supported

### ISSUE THREAD

**Issue by lordcyb3r** [DesktopECHO/Pi-Hole-for-WSL1#21]
[log.txt](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/files/6720752/log.txt)

**Comment by lordcyb3r** [comment]
needs PIHOLE_SKIP_OS_CHECK=true (details in log)

**Comment by lordcyb3r** [comment]
### FIX
Pi-hole Configuration.cmd:
@"C:\[install path]\Pi-hole\LxRunOffline.exe" r -n Pi-hole -c  "echo 'nameserver 1.1.1.1' > /etc/resolv.conf ; **PIHOLE_SKIP_OS_CHECK=true** pihole -r"

Pi-Hole Launcher.cmd:
(line 74)
%GO% "echo 'nameserver 1.1.1.1' > /etc/resolv.conf ; curl -L https://install.Pi-hole.net | **PIHOLE_SKIP_OS_CHECK=true** bash /dev/stdin --unattended"

**Comment by DesktopECHO** [comment]
What version of Windows are you on?   
Example: 

```C:\Users\Lab>ver.exe```

```Microsoft Windows [Version 10.0.17763.1999]```

Sound like you're missing the last WSL update
See README.md:

**IMPORTANT! Requires August/Sept 2020 WSL update for Windows 10.** This update is already included in Windows 20H2 and newer. If you don't have Windows up to date, Pi-hole installer will throw an "Unsupported OS" error midway through the installation.  If this occurrs, run the Pi-hole uninstaller, update your operating system and try again.  Minimum required updates are as follows:**

* 1809 - KB4571748
* 1909 - KB4566116
* 2004 - KB4571756

**Comment by lordcyb3r** [comment]
ive made sure I am up to date. This was more to post my solution so that others have a fix. also there is not a downside to having that flag set, It just skips compatibility checking.

**Comment by lordcyb3r** [comment]
also since I have an issue here already I have a suggestion (rather than open a new thread).
It would be nice to have 2 separate versions, one with cloudflared and one with out. DoH is in beta and has a few minor issues that some won't like. Plus, some people (like vpn users) won't need it as dns is already encrypted.

**Comment by DesktopECHO** [comment]
Looking at your logfile, it appears that you have a DNS issue or something is blocking traffic:
 ```
 [✗] Retrieval of supported OS list failed. dig failed with return code 9.
      Unable to determine if the detected OS (Debian 10) is supported
      Possible causes for this include:
        - Firewall blocking certain DNS lookups from Pi-hole device
        - ns1.pi-hole.net being blocked (required to obtain TXT record from versions.pi-hole.net containing supported operating systems)
        - Other internet connectivity issues
```
I just ran the install and didn't see any issues:

![image](https://user-images.githubusercontent.com/33142753/123558494-eb5b4880-d76c-11eb-9ba5-35db896fb9d1.png)
