### ISSUE TITLE
i dont have Pi-hole for Windows option on task sheduler?

### ISSUE THREAD

**Issue by CilginFlix** [DesktopECHO/Pi-Hole-for-WSL1#26]
i did everything and it is working. but i dont have Pi-hole for Windows option and i tryed to reboot my pc to see how it works and of course it was not working and no Pi-hole for Windows option.

btw it is my main pc i want to use it only on my pc...

**Comment by DesktopECHO** [comment]
Hi are you a local administrator on your PC?  Is the computer joined to a domain?

**Comment by azamet90** [comment]
i think im local admin... im not sure because of my bad english and my first time to use somethings like that. im just a normal windows 10 user. no domain...

**Comment by azamet90** [comment]
and after reinstalling it i only can access to panel from 127.0.0.1/admin no more username/admin

**Comment by DesktopECHO** [comment]
Paste these lines into a PowerShell window to tell if the console session is running as administrator.  If you are admin it will respond with 'true'

`````$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())`````
`````$currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)`````

Run this to verify that the Scheduled Task was created:
`````schtasks | findstr Pi-hole`````

You should see:
`````Pi-hole for Windows                      N/A                    Ready`````

If you are local admin but the task does not exist, see [this issue](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/issues/5#issuecomment-703198780) on how to create the scheduled task manually.

**Comment by azamet90** [comment]
> 
> 
> Paste these lines into a PowerShell window to tell if the console session is running as administrator. If you are admin it will respond with 'true'
> 
> `$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())`
> `$currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)`
> 
> Run this to verify that the Scheduled Task was created:
> `schtasks | findstr Pi-hole`
> 
> You should see:
> `Pi-hole for Windows N/A Ready`
> 
> If you are local admin but the task does not exist, see [this issue](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/issues/5#issuecomment-703198780) on how to create the scheduled task manually.

on that command u said i get this error sir: ERROR: There was nothing between user accounts and security IDs.

**Comment by DesktopECHO** [comment]
Please paste the output into this this thread, like so:

![image](https://user-images.githubusercontent.com/33142753/134680192-9c20970c-0255-4d41-aa4a-8de5213901c9.png)

**Comment by azamet90** [comment]
> 
> 
> Please paste the output into this this thread, like so:
> 
> ![image](https://user-images.githubusercontent.com/33142753/134680192-9c20970c-0255-4d41-aa4a-8de5213901c9.png)

i did this and its "True" but the second command output is empty... so i tryed to manually create it with that command u give on other topic but its giving me that error: ERROR: There was nothing between user accounts and security IDs.

**Comment by DesktopECHO** [comment]
Try this instead:

`````SCHTASKS /CREATE /RL HIGHEST /SC ONSTART /TN "Pi-hole for Windows" /TR '"C:\Program Files\Pi-hole\Pi-hole_Task.cmd"' /F`````

Does it create the scheduled task? If so, open Task Scheduler and try to run it and see if it works.

**Comment by azamet90** [comment]
okay it did work. thanks for help! but is it okay that admin/user domain is not working? i only can access over 127.0.0.1 to pihole panel...

**Comment by DesktopECHO** [comment]
Sorry I don't understand the question.  What do you mean by "_is it okay that admin/user domain is not working_"

When you run the Pi-hole install script, it allows you to set a password for the web admin page at http://localhost/admin
If your computer's internal IP is (for example) 192.168.0.2 then you can access the same page from other computers on your network at http://192.168.0.2/admin

**Comment by azamet90** [comment]
okay thanks! this was my question. before i was able to login to panel with that domain http://admin/user or http://user/admin i dont remember but after reinstall its just gone. but if u mean its okay than its okay.

**Comment by DesktopECHO** [comment]
Glad to hear you're up and running.  
'Crazy'-flix, right?  Hope to see Istanbul next year I hear it's a cool place to visit!
D.
