### ISSUE TITLE
Does not proceed after install dependencies

### ISSUE THREAD

**Issue by donperryrr** [DesktopECHO/Pi-Hole-for-WSL1#27]
I have tried to install and uninstall, update windows, disable AV. but mine did not proceed on install dependencies.

Please see ss. 

Thanks for your effort! really wanted to make this work

![image](https://user-images.githubusercontent.com/90419360/132752129-6dc4cb5f-9394-48b0-b9c5-ed178a3736e6.png)

**Comment by waji1305** [comment]
![image](https://user-images.githubusercontent.com/90513151/133914038-8e7b0df7-b0c8-4a00-93fe-690ad63fa89f.png)

hi there, mine also can't work as well. Very appreciate if anyone could help. Thank you

**Comment by DesktopECHO** [comment]
This screenshot looks ok.  
What happened after you "Press any key to continue . . ."

**Comment by DesktopECHO** [comment]
What version Windows are you on?  
Ex:  [Version 10.0.19043.1237]
