### ISSUE TITLE
Can't work after installation, "The is no distribution with the supplied name"

### ISSUE THREAD

**Issue by waji1305** [DesktopECHO/Pi-Hole-for-WSL1#28]
I've tried everything in order and now I'm stuck at this stage. What should I do? Very appreciated it if you could help. Thank you

![image](https://user-images.githubusercontent.com/90513151/133914078-0a946009-a2b3-4b18-829e-70332b8991b2.png)

**Comment by DesktopECHO** [comment]
Looks like a corrupt download.  Run the uninstaller as Administrator, and attempt to reinstall.

**Comment by waji1305** [comment]
I've tried it and works thank you.
