### ISSUE TITLE
Question: ability to use existing WSL1 installation?

### ISSUE THREAD

**Issue by rocwhite168** [DesktopECHO/Pi-Hole-for-WSL1#29]
In the spirit of being more light weight, is it possible to use the installer with an existing WSL1 installation without having to download and install Debian 10?

**Comment by DesktopECHO** [comment]
Hi, the existing Debian 9 download is just 77.1MB. 
A clean install of a distro ensures the script will run smoothly and predictably every time.  It's recommend to let the installer create its own Debian instance and just treat Pi-hole like any other Windows application.  That said, there's nothing preventing you from taking the Pi-hole-specific bits out of the script and adapting them for your own use.

**Comment by rocwhite168** [comment]
For me, right after installation, it uses about 697MB, which feels a bit bloated for a standalone app. Also I assume I have to remember to `apt update` the Pi-hole installation regularly? Would you consider providing a listing of places to change? I can roughly follow and figure out the script but would feel much more reassured with the developer's confirmation/blessing :)

**Comment by DesktopECHO** [comment]
The distro self-updates using [unattended-upgrades](https://wiki.debian.org/UnattendedUpgrades).
