### ISSUE TITLE
No Distribution Available?

### ISSUE THREAD

**Issue by trevor68** [DesktopECHO/Pi-Hole-for-WSL1#30]
After copying the CMD file to my W10 PC and running as admin, it seems to be not finding anything to download?

This is on a newly installed NUC running up to date 21H1.
![nodistro](https://user-images.githubusercontent.com/91324171/134671817-4b633115-da71-4fcd-bba4-ae47245c9124.jpg)

**Comment by DesktopECHO** [comment]
Hi there -- Run the uninstaller as administrator, empty your %TEMP% folder, and retry the installation.  What kind of AV are you running?  

As a test, are you able to download the distro by running the command below?

`````POWERSHELL.EXE -Command "Start-BitsTransfer -source https://salsa.debian.org/debian/WSL/-/raw/6fb6134911e7c25bfd78635a70649b94f82773b0/x64/install.tar.gz?inline=false -destination '%TEMP%\buster.tar.gz'"`````

**Comment by trevor68** [comment]
Windows Defender with the Firewall turned off. I emptied %TEMP% and tried again to the same result. The script you posted seems to have downloaded buster fine, it is in the temp folder at about 79001kb,

Re my environment, I agree, I was trying to use Docker originally, so I uninstalled Docker, Debian and set WSL default back to 1. I guess that wasn't enough to clean it up :-(

**Comment by trevor68** [comment]
All good, I blew the nuc away and on a fresh install the script worked like a charm, many thanks! :-)
