### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by trevor68** [DesktopECHO/Pi-Hole-for-WSL1#32]
More of a noob question really, how do I update pihole?

I get unknown command if I run pihole -up from CMD?

**Comment by DesktopECHO** [comment]
- Run the Pi-hole updater:
```"C:\Program Files\Pi-hole\LxRunOffline.exe" r -n Pi-hole -c  "pihole -up"```

- Then install the WSL fix-ups, run:
```"C:\Program Files\Pi-hole\Pi-hole Configuration.cmd"```
- Select "Repair" 

Pi-hole will re-launch with the latest version.

**Comment by DesktopECHO** [comment]
Updated installer with shortcut for "Pi-hole Updater"

**Comment by Kallamamran** [comment]
<img width="522" height="59" alt="Image" src="https://github.com/user-attachments/assets/42bb348e-b627-4947-b243-952d88902bfc" />
