### ISSUE TITLE
Possible to add recursive DNS to the script?

### ISSUE THREAD

**Issue by wazerstar** [DesktopECHO/Pi-Hole-for-WSL1#35]
I saw this video and would be cool to get as an option or just included..

https://www.youtube.com/watch?v=FnFtWsZ8IP0

What do you think?

**Comment by DesktopECHO** [comment]
Done.  Give it a try and let me know how it works.

**Comment by wazerstar** [comment]
> Done. Give it a try and let me know how it works.

Works brilliant on my normal windows machine with windows 10 pro! 👍 💯 

Now comes something that bugs out..

Currently running the script on my raspberry pi4 8gb with windows 11 pro installed on it.

it gives error with fstab mount error.

A little video from installation..

**Comment by DesktopECHO** [comment]
I'm surprised it even got that far!  This installer is meant for x86-64 systems, so an rPi (which uses an ARM processor) won't work.  Unfortunately I don't have any ARM hardware that can run Windows to replicate the issue.  

If you have an rPi and want Pi-hole, best do it in Linux.  That said, I salute your efforts to cajole hardware into running stuff it was never meant to run!

**Comment by wazerstar** [comment]
> I'm surprised it even got that far! This installer is meant for x86-64 systems, so an rPi (which uses an ARM processor) won't work. Unfortunately I don't have any ARM hardware that can run Windows to replicate the issue.
> 
> If you have an rPi and want Pi-hole, best do it in Linux. That said, I salute your efforts to cajole hardware into running stuff it was never meant to run!

I'm sure I'll get it to run just need some time to sort out the issues :D

**Comment by DesktopECHO** [comment]
> > I'm surprised it even got that far! This installer is meant for x86-64 systems, so an rPi (which uses an ARM processor) won't work. Unfortunately I don't have any ARM hardware that can run Windows to replicate the issue.
> > If you have an rPi and want Pi-hole, best do it in Linux. That said, I salute your efforts to cajole hardware into running stuff it was never meant to run!
> 
> I'm sure I'll get it to run just need some time to sort out the issues :D

I agree, in theory this should work for you.  If the two architectures don't diverge too much I'll consider adding logic in the installer to accommodate both of them.  
Start off by modifying the script to download the right architecture for your rPi instead of the x86-64 version:

`https://salsa.debian.org/debian/WSL/-/raw/master/ARM64/install.tar.gz?inline=false`

Closing this issue as we've sorted out the inclusion of Unbound in the installer.
Please open a new one for ARM installation if you have any further questions.

**Comment by DesktopECHO** [comment]
> > I'm surprised it even got that far! This installer is meant for x86-64 systems, so an rPi (which uses an ARM processor) won't work. Unfortunately I don't have any ARM hardware that can run Windows to replicate the issue.
> > If you have an rPi and want Pi-hole, best do it in Linux. That said, I salute your efforts to cajole hardware into running stuff it was never meant to run!
> 
> I'm sure I'll get it to run just need some time to sort out the issues :D

It happened! 

https://github.com/DesktopECHO/Pi-Hole-for-WoA




> > Done. Give it a try and let me know how it works.
> 
> Works brilliant on my normal windows machine with windows 10 pro! 👍 💯
> 
> Now comes something that bugs out..
> 
> Currently running the script on my raspberry pi4 8gb with windows 11 pro installed on it.
> 
> it gives error with fstab mount error.
> 
> A little [video](https://streamable.com/dt8jiv) from installation..

It happened!
https://github.com/DesktopECHO/Pi-Hole-for-WoA
