### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by JakkzGH** [DesktopECHO/Pi-Hole-for-WSL1#36]
I've been trying to get this set up on my personal computer for an hour and I keep getting the same errors every time. I've tried different install paths, and I've tried a couple of fixes I found on Reddit to no avail. I also didn't see this specific error in any previous Issues posts. I'm on Windows 10 Home 21H2. The second screenshot is what happens if I hit continue; it just tries to connect to "http://desktop-rsrrmpt/admin" with (desktop-rsrrmpt) being my personal computer's name.
![github](https://user-images.githubusercontent.com/96995149/147886484-30670240-f40b-43c0-9b09-79e392099b59.png)
![image](https://user-images.githubusercontent.com/96995149/147886557-2f7abb63-2b38-4a13-b559-d8058b771a49.png)

**Comment by DesktopECHO** [comment]
Hi - Have you tried (run the uninstaller first as admin) installing in the default location (C:\Program Files) or somewhere other than your root drive?)

**Comment by thelunchboxosu** [comment]
I'm think I'm having a similar experience. I'm updated to the the same update, after a fresh install of windows 10 pro. I have uninstalled as admin, deleted temp folders, reinstalled as ain, and still get the OS error. I get a server 404 error once the installer finishes and opens a browser.

**Comment by DesktopECHO** [comment]
I’ll try to reproduce when I get back online in a few hours.

**Comment by JakkzGH** [comment]
I have tried installing it in different directories and the default directory, however, I've just been manually deleting the installed PiHole files instead of using the uninstall cmd. It seems to be doing something now...
![image](https://user-images.githubusercontent.com/96995149/147888572-dbc04a95-e18f-4ceb-b1d2-3cf9e0363a55.png)

**Comment by DesktopECHO** [comment]
Excellent!  @thelunchboxosu please open a separate issue and post a screenshot
