### ISSUE TITLE
Not installing in Windows 10, even though updated to most current update

### ISSUE THREAD

**Issue by thelunchboxosu** [DesktopECHO/Pi-Hole-for-WSL1#37]
![Screenshot_20220104-220053.png](https://user-images.githubusercontent.com/593695/148154620-011f52a8-2c3e-4994-aabc-922a580a661a.png)

![Screenshot_20220104-220334.png](https://user-images.githubusercontent.com/593695/148154634-b4e49175-e5fb-493b-a418-a95cee51830e.png)

![Screenshot_20220104-220349.png](https://user-images.githubusercontent.com/593695/148154647-f280cc1f-23f4-4cea-acae-50f7dee2dfb6.png)

![Screenshot_20220104-220516.png](https://user-images.githubusercontent.com/593695/148154666-80f9b85a-1ada-4770-9e66-ec58e11ec9e2.png)

![Screenshot_20220104-220708.png](https://user-images.githubusercontent.com/593695/148154688-65e9dcbb-d5cb-4c79-9cb6-fcc9df59c393.png)

**Comment by DesktopECHO** [comment]
Hi, 

First, run the uninstaller to remove the failed attempt.  

Next, temporarily set your DNS server in Windows to 1.1.1.1 before you run the installer.

Finally, run PH4WSL1.CMD as administrator.  Let’s see how that works.

**Comment by thelunchboxosu** [comment]
Thanks so much for helping out! Walked through that process, unfortunately had the same results. 😅

![Screenshot_20220104-222530.png](https://user-images.githubusercontent.com/593695/148157297-178a9737-f3e7-49cb-9556-ebe65261f155.png)

![Screenshot_20220104-223528.png](https://user-images.githubusercontent.com/593695/148157311-5782dc46-eef8-4711-ae2a-1394b29d15c4.png)

![Screenshot_20220104-223635.png](https://user-images.githubusercontent.com/593695/148157324-86168b41-b017-4763-89ae-29857fc074ea.png)

![Screenshot_20220104-223947.png](https://user-images.githubusercontent.com/593695/148157332-c528ed44-869f-45f2-86ae-b71ed0a50f77.png)

![Screenshot_20220104-224019.png](https://user-images.githubusercontent.com/593695/148157340-a66a33c2-3450-4cfb-8e42-38da5ceedc21.png)

**Comment by DesktopECHO** [comment]
Give me a few minutes I'm going to spin the installer on a lab machine... maybe there is an issue upstream.

**Comment by DesktopECHO** [comment]
What is the output from the following command on your Windows PC?

`````nslookup -type=ns ns1.pi-hole.net`````

**Comment by DesktopECHO** [comment]
Not seeing any issues over here so far...

![image](https://user-images.githubusercontent.com/33142753/148160760-3f46e41a-1659-48d8-88aa-d8b866efc4b3.png)

**Comment by DesktopECHO** [comment]
Also, what is the output from:

`````nslookup -type=txt versions.pi-hole.net`````

**Comment by thelunchboxosu** [comment]
> What is the output from the following command on your Windows PC?
> 
> `````nslookup -type=ns ns1.pi-hole.net`````
>

**Comment by DesktopECHO** [comment]
Hi there, give this a try please.  Edit the script, find line:

`````%GO% "echo 'nameserver 1.1.1.1' > /etc/resolv.conf ; curl -L https://install.Pi-hole.net | bash /dev/stdin --unattended"`````

Change it to:

`````%GO% "echo 'nameserver 1.1.1.1' > /etc/resolv.conf ; PIHOLE_SKIP_OS_CHECK=true curl -L https://install.Pi-hole.net | bash /dev/stdin --unattended"`````

Save the file, run the uninstaller, then run the modified installer and we'll see if that gets us any farther ahead.

**Comment by thelunchboxosu** [comment]
> Hi there, give this a try please. Edit the script, find line:
> 
> `%GO% "echo 'nameserver 1.1.1.1' > /etc/resolv.conf ; curl -L https://install.Pi-hole.net | bash /dev/stdin --unattended"`
> 
> Change it to:
> 
> `%GO% "echo 'nameserver 1.1.1.1' > /etc/resolv.conf ; PIHOLE_SKIP_OS_CHECK=true curl -L https://install.Pi-hole.net | bash /dev/stdin --unattended"`
> 
> Save the file, run the uninstaller, then run the modified installer and we'll see if that gets us any farther ahead.

>
![1_7 error](https://user-images.githubusercontent.com/593695/148618496-04536c0c-9e6c-4388-864e-64b55409374d.png)

**Comment by DesktopECHO** [comment]
My bad.... let me give you the correct instructions:

Find line:

`````%GO% "echo 'nameserver 1.1.1.1' > /etc/resolv.conf ; curl -L https://install.Pi-hole.net | bash /dev/stdin --unattended"`````

Change it to:

`````%GO% "echo 'nameserver 1.1.1.1' > /etc/resolv.conf ; curl -L https://install.Pi-hole.net | PIHOLE_SKIP_OS_CHECK=true bash /dev/stdin --unattended"`````

**Comment by DesktopECHO** [comment]
Just pushed an update.... Try uninstalling an re-installing the latest commit from GitHub

**Comment by thelunchboxosu** [comment]
> My bad.... let me give you the correct instructions:
> 
> Find line:
> 
> `````%GO% "echo 'nameserver 1.1.1.1' > /etc/resolv.conf ; curl -L https://install.Pi-hole.net | bash /dev/stdin --unattended"`````
> 
> Change it to:
> 
> `````%GO% "echo 'nameserver 1.1.1.1' > /etc/resolv.conf ; curl -L https://install.Pi-hole.net | PIHOLE_SKIP_OS_CHECK=true bash /dev/stdin --unattended"`````
> 

Just tested this before you posted about an update and this worked!

**Comment by thelunchboxosu** [comment]
> Just pushed an update.... Try uninstalling an re-installing the latest commit from GitHub

This worked flawlessly as well!

**Comment by DesktopECHO** [comment]
>> Just pushed an update.... Try uninstalling an re-installing the latest commit from GitHub

> This worked flawlessly as well!

Excellent!  Thanks for testing out the latest release... enjoy!
D.
