### ISSUE TITLE
can we get uninstall instructions

### ISSUE THREAD

**Issue by TheClassic** [DesktopECHO/Pi-Hole-for-WSL1#38]
I decided Pihole isn't for me. I'd love to understand how to uninstall it and remove any configuration changes it made, specifically the installation of Debian linux? Can a short guide me added to the end of the readme?

**Comment by DesktopECHO** [comment]
There’s an uninstaller in C:\Program Files\Pi-hole.  Run it as administrator so it’s able to remove the firewall rules as well.

**Comment by DesktopECHO** [comment]
FYI, his information is already in the readme.

**Comment by TheClassic** [comment]
Doesn't this only remove Pihole, while the PH4WSL1.cmd like getting a linux subsystem running that stays updated?

**Comment by DesktopECHO** [comment]
The uninstaller deletes the entire Debian distro that PH4WSL1.CMD built for you.
