### ISSUE TITLE
Installer error: Cannot open netlink socket: Protocol not supported

### ISSUE THREAD

**Issue by cayers10** [DesktopECHO/Pi-Hole-for-WSL1#39]
Receiving this error when installing. 

Tried uninstall/reinstall with the same behavior

![image](https://user-images.githubusercontent.com/97293123/148547549-6cb51614-686f-4a4f-bbe4-cc8255c53e10.png)

**Comment by DesktopECHO** [comment]
Does the Pi-hole web interface look ok, and is handling DNS queries?
This breakage is due to the recent update upstream, but it's only cosmetic.  I'm working on a fix this weekend.

**Comment by cayers10** [comment]
Web UI and DNS handling is working properly. Thank you!

**Comment by DesktopECHO** [comment]
Hi there, I pushed out an update to clean up the install.
If you want to get rid of those cosmetic issues you can uninstall and re-install the script.

**Comment by DesktopECHO** [comment]
* Download the latest version from github first before re-installing, just to be clear.
