### ISSUE TITLE
RAM shortage / Disk shortage warnings when it's not really a shortage.

### ISSUE THREAD

**Issue by FDisk80** [DesktopECHO/Pi-Hole-for-WSL1#40]
```
RAM shortage (/dev/shm) ahead: 92% used
/dev/shm: 923.0GB used, 999.1GB total, FTL uses 717.1KB
```

```
Disk shortage (/etc/pihole/pihole-FTL.db) ahead: 92% used
/etc/pihole: 923.1GB used, 999.1GB total
```

```
Disk shortage (/var/log/pihole-FTL.log) ahead: 92% used
/var/log: 923.1GB used, 999.1GB total
```

Sure, it 92% full. But there is still 76GB of free space left.

**Comment by DesktopECHO** [comment]
Enter the Linux console:

``wsl -d Pi-hole``

Set an override to the threshold level, 98% in this example:

``echo "CHECK_DISK=98" >> /etc/pihole/pihole-FTL.conf``

Exit the Linux console:

``exit``

Restart Pi-Hole:

``"C:\Program Files\Pi-hole\Pi-hole Launcher.cmd"``

**Comment by FDisk80** [comment]
> CHECK_SHMEM=0

**Comment by FDisk80** [comment]
Thank you. That worked perfectly.
