### ISSUE TITLE
Gravity Update

### ISSUE THREAD

**Issue by peppeve** [DesktopECHO/Pi-Hole-for-WSL1#41]
There is a way to create a .cmd file for gravity update? Thanks so much for the job, my pihole work great in a VPS with Windows Server 2019.

**Comment by DesktopECHO** [comment]
Glad to hear it!

You can update gravity by running the following command:

``wsl -d Pi-hole pihole updateGravity``

**Comment by peppeve** [comment]
Thanks again.
