### ISSUE TITLE
DNS settings after script install without docker etc

### ISSUE THREAD

**Issue by what-aboot** [DesktopECHO/Pi-Hole-for-WSL1#42]
Hi DesktopECHO, 

Your PH4WSL1.cmd script was just what I needed. Thank you SO much!

### It Worked!
No having to learn about distros, docker, hyperV, Virtualbox - just run the script, it does everything. Which it did. The only hassle is I can't find how to set the Pihole as the DNS server on my particular setup. All of googles replies are about setting routers, or Docker, or HyperV, etc.

### My setup
1. I have only one Win 10 Pro desktop, which I use to run Anaconda, surf the net, play various Steam games on, named ZEN
2. I use my mobile phone hotspot to connect to the internet, ie there is no router. 

       (ZEN/Browser) ---> (ZEN/Wireless LAN adapter WiFi) ---> (Android/Hotspot)

and I want to change it to

      (ZEN/Browser) ---> (ZEN/WSL/PiHole) ---> (ZEN/Wireless LAN adapter WiFi) ---> (Android/Hotspot)

### PiHole Setup Works
I have run your script and pihole tells me it is running
- i .   If I open the browser at "http://zen/admin/index.php" I get the dashboard

![PIHOLE DNS](https://user-images.githubusercontent.com/92685830/149671814-6e9baef7-bec9-415d-8657-e7835a960902.png)

- ii.   If I open Powershell and type wsl, I get "root@ZEN:/mnt/c/Users/User#"

- iii.  It reports Pi-hole as the version of linux installed
![PIHOLE running](https://user-images.githubusercontent.com/92685830/149671768-17ffb276-84cc-4dd3-b232-a8321429210e.png)

But it's not logging/blocking anything

### Data Flow
I know that the normal setup is 
        PC ---> Router ---> Internet

and that one sets up PiHole as the DNS on the router so that the flow is 
        PC request --> Router --> Pihole --> (either block or send upstream eg Google)

but without a router, I can't get my head around, setting this flow up
        PC request --> WSL--> Pihole --> (either block or send upstream eg Google)

### Attempts
I tried setting the Wifi card as static DNS and it connected, no internet (it no longer worked). 
Win 10 troubleshooter set it back to DHCP and it worked again.

### Request
What I'm looking for is literally a set of steps to achieve PiHole between the PC and the hotspot.
It would be nice to know what the flow is when the Win 10 PC making the request is the same PC hosting PiHole on WSL and the internet has no router just a USB wifi dongle receiving from an Android 10 mobile?

ie (ZEN/Chrome) ---> (ZEN/WSL/PiHole) ---> (ZEN/Wireless LAN adapter WiFi) ---> (Android/Hotspot)

It may help if you added this knowledge to the end of your writeup on PH4WSL1.cmd. There are bound to be others like me needing a quick n easy way.

(Pardon the rambling issue description - I used to be a software developer but then I had a burnout and I cannot follow simple instructions any more, so things like MAN pages and PiHole's own documentation blow my mind.  After reading that I'd have to have another licence to run windows inside HyperV just about made me give up, then I found your page)

**Comment by DesktopECHO** [comment]
Hi... It looks like everything is set up and ready to go.  All that's left to do is tell your PC to use Pi-hole instead of your DHCP-assigned DNS.
Have a look at the [installation walk-through](https://youtu.be/keDtJwK65Dw) on YouTube around 1:10
Leave your IP as DHCP but set the DNS manually to 127.0.0.1 and you should be good to go!

**Comment by DesktopECHO** [comment]
Hi there did you get your issue sorted out?  If so I’ll close the incident.

**Comment by what-aboot** [comment]
Hi, it didn't actually, but the idea was right. What worked was to totally uninstall Pihole, then reinstall. It collected the settings it had re DNS and then worked. So, yes, close the issue. 

Thanks for your very quick response.

What I've gone on to do is turn Pihole into a recursive DNS which is working perfectly, using Unbound and the script from Pihole themselves.

What about adding a link to that from your write up? Anything to make the journey lighter for them that follow...

**Comment by DesktopECHO** [comment]
Just to be clear, you uninstalled Pi-hole using ``Pi-hole Uninstall.cmd`` or uninstalled/reinstalled in the Linux instance?

**Comment by what-aboot** [comment]
using Pi-hole Uninstall.cmd

**Comment by DesktopECHO** [comment]
Got it... Thanks for the update, glad to hear it's working for you.

**Comment by what-aboot** [comment]
Hi
Sorry to ask this way, but I can't find anyone to answer it.

My pi, hole has been running fine after having used your script.

My challenge is that I can't remember how to get to the linux prompt. I've
opened a admin cmd prompt, and cd'd all the way to rootfs under pihole, but
it's still not recognising forward slash commands, and has no idea what
nano is - so how do i start the linux / or get to be able to type Linux
commands?

Thanks

Dennis

**Comment by DesktopECHO** [comment]
Hi, you want this command:
wsl -d Pi-hole

**Comment by what-aboot** [comment]
Hi
Thank you so much for all the wonderful scripts you've made.

I'll happily buy you a coffee if you tell me how... (btw I'll be at Changi
on the night of 30 Nov 2022, but the coffee'll probably be cold by then)

I'm just looking at putting Pi-Hole on my phone as I'm having issues with
blokada. Your script says 'rooted phone' and mine's not rooted, so that's
my current research task, but I came across this video on installing Kali
on a non-rooted phone and wondered if similar process could be used for the
Pi-Hole on Android?

https://www.youtube.com/watch?v=zcIwIhqT7Pc

Also, is there a way to clone the Pi-Hole I've installed on WSL?



Dennis

**Comment by DesktopECHO** [comment]
Hi,
- Root is mandatory because DNS listens on a low port, so the approach used in that video (pRoot) won't work.
- [LXRunOffline](https://github.com/DDoSolitary/LxRunOffline) is in your install folder, it can help you archive the `rootfs` folder.  You'll need to do the CMD scripts separately if you want to keep them. 

Thanks for the kind words, always good to hear success stories!
