### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by LeanUnderscore** [DesktopECHO/Pi-Hole-for-WSL1#43]
Hello, the issue I'm having is on a win10 machine where I get the administrator check and then the program closes instantly.

I have tried:
enabling / disabling UAC control
deleting temp folder and restarting
adding PAUSE at the end of the code to view error

Win10 Pro
Version: 21H2
OS Build: 19044.1466
Experience pack: 120.2212.3920.0

https://user-images.githubusercontent.com/98245904/150663401-b79ac891-d721-431e-8f8e-451f36fa4575.mp4

**Comment by DesktopECHO** [comment]
Hi I’m not near a PC at the moment, but try right-clicking the file and click properties.  Near the bottom do you see an option to unblock the file?

**Comment by LeanUnderscore** [comment]
I do not, I forgot to mention I've turned off all antivirus and made sure that port 80 is open

**Comment by DesktopECHO** [comment]
Try downloading the script again, and removing the administrator check (line 3) to see if that gets you any farther ahead.

**Comment by DesktopECHO** [comment]
One more idea… try to open a command prompt (as admin) and run the script from there.  That way we can see if there’s any output as the window won’t close when you run it that way.

**Comment by DesktopECHO** [comment]
And finally… try adding the WSL role in Windows so the script doesn’t have to do it on it’s own.  Will try to replicate the issue tomorrow.

**Comment by LeanUnderscore** [comment]
![2022-01-22 22_40_03-192 168 0 251 - Remote Desktop Connection](https://user-images.githubusercontent.com/98245904/150667762-0fc53dde-6b5e-41e7-a463-ef4c285b1b2d.png)

This is after removing line (3) and running through CMD with Admin rights

**Comment by LeanUnderscore** [comment]
Looks like it made it to enabling WSL so the error must be past it (I did not enable this)
![2022-01-22 22_45_42-192 168 0 251 - Remote Desktop Connection](https://user-images.githubusercontent.com/98245904/150667838-bb4f30e7-2d49-49d0-af1b-d9d0ff800131.png)

**Comment by DesktopECHO** [comment]
> ![2022-01-22 22_40_03-192 168 0 251 - Remote Desktop Connection](https://user-images.githubusercontent.com/98245904/150667762-0fc53dde-6b5e-41e7-a463-ef4c285b1b2d.png)
> 
> This is after removing line (3) and running through CMD with Admin rights

Hi please remove line 2 as well and retry.

**Comment by LeanUnderscore** [comment]
after removing #2 and #3 I get thi
![2022-01-22 22_52_24-192 168 0 251 - Remote Desktop Connection](https://user-images.githubusercontent.com/98245904/150668023-12e46fb5-6f82-46cb-92c3-d26014405595.png)
s

**Comment by DesktopECHO** [comment]
Ok… I think it maybe that single quote in your username.  Can you create a new user with admin rights and try from there?

**Comment by LeanUnderscore** [comment]
I removed line #7 and got it to install.
 (IF %SIZE% gtr 0 SET PORT=60080) 
must have been getting 0 and not knowing what to do?

**Comment by LeanUnderscore** [comment]
Now it's not entirely working but could be on my end. 
![2022-01-22 23_04_45-192 168 0 251 - Remote Desktop Connection](https://user-images.githubusercontent.com/98245904/150668308-a2b307d2-d54e-4349-ab78-04aca3533a79.png)

worst case scenario I will run the uninstaller create a new acc and run it from there....

**Comment by DesktopECHO** [comment]
Have to go offline but let me know how things go with a new user account.  I’m pretty sure it will work after that.

**Comment by LeanUnderscore** [comment]
Will do, thank you for the help

**Comment by LeanUnderscore** [comment]
changed user profile with no funky syntax, Installer got much further until
![2022-01-22 23_19_15-192 168 0 251 - Remote Desktop Connection](https://user-images.githubusercontent.com/98245904/150668636-bc391574-feef-45d4-9309-d4f150831e62.png)

**Comment by DesktopECHO** [comment]
That’s a totally different error, on the top see it says server can’t be resolved… Is your DNS set to a working server?

**Comment by LeanUnderscore** [comment]
You were correct it was a DNS issue for me. Using another account worked great. thank you very much for your help!
