### ISSUE TITLE
wrong terminal?

### ISSUE THREAD

**Issue by CZTeo** [DesktopECHO/Pi-Hole-for-WSL1#44]
when i ran the installer it opened command prompt instead of powershell and after installing i cant access the admin page i wonder if thats the reason i cant go to the admin page on my browser

**Comment by DesktopECHO** [comment]
Hi, run the uninstaller as administrator and re-run the installer.

**Comment by Sinusflorian** [comment]
Hello, i have the same Issue, i can uninstall and rerun in Admin mode but it just starts CMD and not PowerShell.

**Comment by Sinusflorian** [comment]
![Screenshot (476)](https://user-images.githubusercontent.com/93134772/151145982-29d7e6f7-aff5-4041-8682-9825b47158f6.png)
This is what always happens. i uninstalled it for now and waiting for update, maybe windows did today break it with some Updates ^^

**Comment by Sinusflorian** [comment]
Ok i retried it 4 times and then the install in CMD passed successfully but when the browsertab opening, then nothing shows up, just that it don't exist. ok i now ill wait for response, have to go off from PC now anyways.

**Comment by Sinusflorian** [comment]
Ok i got it^^ had to disable Kaspersky until the installation and the first startup, then it work and THEN when you reanable Kaspersky it will ask you to make exceptions and THEN you are good to go! 

P.S. Proud to solved something technically lol not the best at PCthingys ^^ 

P.S2: Damn imn stupid^^ readed when i was on google search that i can put that pihole on my Samsung tab 2 too -.-^^ just install that linux lite app and then pihole. Then i don't need to get run the PC all time^^ just cable samsung Tab S2 and modem with a lan adapt cable and lets go XD^^

**Comment by DesktopECHO** [comment]
Hi, good to hear you got it working.  You might be interested in my other [Pi-hole related project](https://github.com/DesktopECHO/Pi-hole-for-Android). :)
