### ISSUE TITLE
Install fail on Curl command

### ISSUE THREAD

**Issue by gkevf** [DesktopECHO/Pi-Hole-for-WSL1#45]
Hi,

OS: Windows 11 Home 10.0.22000 
RAM: 16GB

During the execution of  the install script (ph4wsl1.cmd). The script displayed the following error(s):

**************************************
Launching Pi-hole installer...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0**curl: (6) Could not resolve host: install.Pi-hole.net**
sed: can't read /var/www/html/admin/settings.php: No such file or directory
sed: can't read /var/www/html/admin/settings.php: No such file or directory
sed: can't read /opt/pihole/piholeDebug.sh: No such file or directory
sed: can't read /opt/pihole/piholeDebug.sh: No such file or directory
chown: invalid user: ‘pihole:pihole’
chown: invalid user: ‘pihole:pihole’

Pi-hole Web Admin, /bin/bash: line 1: pihole: command not found

SUCCESS: The scheduled task "Pi-hole for Windows" has successfully been created.

   NOTE! The Scheduled Task needs additional configuration steps
         for Pi-hole to start automatically at boot time.

       - Open Windows Task Scheduler (taskschd.msc)
         Right-click the task "Pi-hole for Windows" and click "Edit"

       - On the General tab, place a checkmark next to both
         "Run whether user is logged on or not" and "Hidden"

       - On the Conditions tab, un-check the option
         "Start the task only if the computer is on AC power"

Press any key to continue . . .
Pi-hole for Windows - Installation complete!
************************************************************************
Note: I uninstalled and reinstalled and also tested the curl -L command using both the URL in the script and the re-directed URL. Both worked from the command line. I'll update this issue if I can make further progress on root cause.

**Comment by DesktopECHO** [comment]
Try this... find this line in the script:

`````%GO% "mv /usr/bin/apt /usr/bin/apt.ph ; echo 'nameserver 1.1.1.1' > /etc/resolv.conf ; curl -L https://install.Pi-hole.net | PIHOLE_SKIP_OS_CHECK=true bash /dev/stdin --unattended ; mv /usr/bin/apt.ph /usr/bin/apt"`````

Change the DNS to your home network's DNS, or in this example, Google's

`````%GO% "mv /usr/bin/apt /usr/bin/apt.ph ; echo 'nameserver 8.8.4.4' > /etc/resolv.conf ; curl -L https://install.Pi-hole.net | PIHOLE_SKIP_OS_CHECK=true bash /dev/stdin --unattended ; mv /usr/bin/apt.ph /usr/bin/apt"`````

**Comment by gkevf** [comment]
Ok, your suggestion worked! I ran the following from the cmd prompt: 

ipconfig /all | findstr "DNS\ Servers"

I then plugged in the ip into the .cmd file and the installation completed. 

Note: I probably should have tried that last night but I ended up focused on the curl command. Thanks for the suggestion and I'll continue to contribute where I can with testing/documentation and or suggestions. I.e., I might try to mod my own version of the script to grab the DNS server IP.

**Comment by DesktopECHO** [comment]
What's very strange is that you can't access CloudFlareDNS...  Are you by chance in Russia or China?

**Comment by DesktopECHO** [comment]
Hi can you try using Quad9 (9.9.9.9) instead?  

If that's not blocked I'll change the script to use that instead.

**Comment by gkevf** [comment]
Hi, 

I was able to successfully get the Quant DNS to install. However, it only worked after turning off my VPN during the installation process. 

Test steps:

1) Uninstalled using the pi-hole uninstall cmd in the pi-hole directory. 
2) Reverted all manual IP config settings for DNS back to 'Auto'
3) Edited the ph4wsl1.cmd file to include the quant DNS server.
4) Rebooted
5) Re-ran install and received "Could not resolve error"
6) Uninstalled
7) Turned off VPN
8) Rebooted
9) Reinstalled 
10) Success

I can get the installation to work on VPN if I specify the VPN DNS IP address in the .cmd file using the ipconfig cmd. I'm also using VPN servers in NA. Everything is fine with Cloudflare if I install without VPN.

**Comment by DesktopECHO** [comment]
Glad to hear you got it working!
