### ISSUE TITLE
Would running a newer version of PH4WSL1.cmd upgrade the system?

### ISSUE THREAD

**Issue by eduo** [DesktopECHO/Pi-Hole-for-WSL1#46]
I used PH4WSL1.cmd a year and change ago. The installation has worked great. I checked today and there's several changes I'm interested in the newer versions. I am not sure how to go about getting them without overwriting the current installation, though.

On one side there's the install mechanism (PH4WSL1.cmd) which would be overwritten. No mention is made of it being used to upgrade (I may be missing it elsewhere than the README).

Then there's the mechanism for upgrading pihole and WSL (as outlined in a couple of comments, but not in the README that I can see):

> Run the Pi-hole updater:
> "C:\Program Files\Pi-hole\LxRunOffline.exe" r -n Pi-hole -c "pihole -up"
> 
> Then install the WSL fix-ups, run:
> "C:\Program Files\Pi-hole\Pi-hole Configuration.cmd"
> 
> Select "Repair"

And there're the uninstall instructions (Pi-hole Uninstall.cmd as admin), in the README.

I can't find how should a newer PH4WSL1.cmd be used to include the newer settings on a running installation.

Could I just download it and rerun and it will understand an existing installation is in place and only add the changes (for example encrypted DNS)?

**Comment by DesktopECHO** [comment]
Hi... best way to proceed:
- Back-up the Pi-hole via the teleporter page (http://pi.hole/admin/settings.php?tab=teleporter)
- Run the Pi-hole for Windows uninstaller (default location C:\Program Files\Pi-hole)
- If the C:\Program Files\Pi-hole folder (or whatever location you chose at install) is not deleted, reboot and manually remove it.
- Run the latest version of PH4WSL1.cmd
- Go back to teleport page and restore settings.

There are a bunch of helper scripts for updating Gravity, updating Pi-hole, and sync between two Pi-hole for Windows instances.
Hope that helps!

**Comment by eduo** [comment]
Thank you for this reply. I read it and it worked but I forgot to come back and let you know.
