### ISSUE TITLE
Install Fails with "Curl: (6) Could not resolve host: install.pi-hole.net"

### ISSUE THREAD

**Issue by adamjthompson** [DesktopECHO/Pi-Hole-for-WSL1#49]
Every time I have tried the install, it fails after the "Launching Pi-Hole Installer" step with the error: "Curl: (6) Could not resolve host: install.pi-hole.net"

I am running Windows 11 on an AMD Ryzen 5600G processor. I have Private Internet Access (VPN software) running on the same system, but I experience the same failure whether it is enabled or not.

I can access that domain directly in a web browser on the same computer. Any ideas on what else to try?

**Comment by DesktopECHO** [comment]
Hi there, give this version in the testing branch a try and let me know if it works for you: [PH4WSL1.CMD](https://raw.githubusercontent.com/DesktopECHO/Pi-Hole-for-WSL1/testing/PH4WSL1.cmd)

**Comment by adamjthompson** [comment]
Well, it failed differently at least. ;-) 
![Screenshot 2022-02-16 135330](https://user-images.githubusercontent.com/2874666/154335801-bc4de972-71bc-47a4-bdbd-f25d085ba6c9.png)

**Comment by DesktopECHO** [comment]
Hi what AntiVirus are you running?  Kapersky and Bitdefender have been toublesome.

**Comment by adamjthompson** [comment]
Only the built-in Windows Defender.

**Comment by DesktopECHO** [comment]
Ok glad to hear it's working in any case.  Enable the scheduled task and it will run reliably forever _(*between reboots)_
