### ISSUE TITLE
NaN on Dashboard

### ISSUE THREAD

**Issue by Kohoboy** [DesktopECHO/Pi-Hole-for-WSL1#50]
Yesterday I set up Pihole on a mini pc that I'm using for my plex server as well (since it was on all the time anyway, I figured might as well add pihole).

I used this github to set it up

I then set the minipc to have a static IP on my network, and used the TP-Link software on my router to set up that static IP as my Primary DNS through the DHCP server settings.

Everything was going great yesterday and the pihole was working very well. I didn't change any settings as of yet, but I did make a backup using the teleporter, just to see how that worked.

All the sudden today I see that on the dashboard the 4 main metric boxes (Total queries, blocked queries, percentage blocked and domains on adlists) all say NaN. The charts and graphs below have spinning circular arrows in the upper left hand corner and display nothing.

The pihole still works just as it did yesterday though. It's blocking the same adds, and if I go into view the long term data, it updates the data, and shows that it's still receiving queries blocking some. I did a restart, and that did nothing.

I supposed it's not a big deal since the pihole is still doing it's job, but is there a way to get the dashboard corrected?

**Comment by Kohoboy** [comment]
Debug token is: http://tricorder.pi-hole.net/igmB6lzE/

**Comment by DesktopECHO** [comment]
Hi there, have you tried restarting Pi-hole?  Open Scheduled Tasks in Windows and run the Pi-hole task to restart.

Unfortunately Windows is an unofficial platform for Pi-hole so I can't view uploaded debug logs.  

Let me know if this is a reoccurring issue and if so we can look at some other troubleshooting steps. 

Thanks,
D.

**Comment by DesktopECHO** [comment]
One more thing... 
Go to the install folder and run "Pi-hole Configuration.CMD" then select "Repair" to see if that corrects the issue.

**Comment by Kohoboy** [comment]
Yes, I restarted pinhole using the reboot in one of the menus, with no success.

Restarting windows entirely did get the graphs back up, but the 4 main metrics display --- now, and multiple restarts haven't changed that.

I can reupload the debug log, the people on Reddit were able to view it, I think it just says it expires after 48 hours, so that is why you were enable to view it.

I'll reply again tomorrow with the updated debug log, as I'm not at home to get it done today.

Thank you

**Comment by Kohoboy** [comment]
Okay, will try the repair function too.

Thank you

**Comment by Kohoboy** [comment]
Restet windows, then restart pihole, then restart windows again, worked.

Appreciate the help.

**Comment by DesktopECHO** [comment]
Good to hear you resolved the issue.  Can you clarify one point -- Did you run "Pi-Hole Configuration.CMD" or just do those restarts?

**Comment by Kohoboy** [comment]
No, just the 3 restarts ended up fixing it.

It had to be in that order though. I tried restarting in other orders and nothing. The only way it ended up fixing it was the specific order of windows, pihole, windows. Otherwise I could restart both as many times as I wanted and still get the same error.
