### ISSUE TITLE
Can't download the debian.tar.gz

### ISSUE THREAD

**Issue by TheHolyG0D** [DesktopECHO/Pi-Hole-for-WSL1#51]
coming to the line;
`IF NOT EXIST %TEMP%\Debian.tar.gz POWERSHELL.EXE -Command "Start-BitsTransfer -source https://salsa.debian.org/debian/WSL/-/raw/master/x64/install.tar.gz?inline=false -destination '%TEMP%\Debian.tar.gz'"`
the download fails, upon looking it up the 'https://salsa.debian.org/debian' page seems to be down
Can we look for some other distro or any means or is this just temporary?

**Comment by DesktopECHO** [comment]
Hi,

This is just temporary, look [here](https://twitter.com/search?q=salsa.debian.org&src=typed_query&f=live) for updates or check back in a little later.

Regards,
D.

**Comment by TheHolyG0D** [comment]
Closing as the issue is not directly related to the script.

**Comment by DesktopECHO** [comment]
Give this a try -- Replace:
``https://salsa.debian.org/debian/WSL/-/raw/master/x64/install.tar.gz?inline=false``
With:
``https://github.com/DesktopECHO/Pi-Hole-for-WSL1/raw/cdf4465044cdfafbc1a0e0098cea5271a217d587/debian11.1b9e7597.tar.gz``

Please report back if that works for you, thanks.

**Comment by TheHolyG0D** [comment]
I tried replacing the URL with the one above, this time it download the image and even installed it, but failed at a certain point, attached is a screenshot
let me know if more details and required.
And thanks for being so responsive :) 
![image](https://user-images.githubusercontent.com/13658447/155997651-e2b53445-6927-453b-993d-2cfb325e6d77.png)

**Comment by TheHolyG0D** [comment]
Few more details:
I'm running it on an ARM64 build for Windows 11 on a Raspberry Pi 4 B 8GB version
Windows is installed using the [Worproject.](https://www.worproject.ml/)
Also, Windows is the latest insider version, Win11 Pro 22563.1
Hyper-V and Virtual Machine Platform have been turned on in the additional Windows Features

![image](https://user-images.githubusercontent.com/13658447/155998947-4ca5eced-982c-41dd-83d6-6f9f720a2adf.png)
![image](https://user-images.githubusercontent.com/13658447/155999255-7802e289-26f8-4e76-89f5-359ee23b4099.png)

**Comment by DesktopECHO** [comment]
Aha ok you are on ARM.

Unfortunately this script will only work on x86-64 systems.  An ARM version may be possible but I don’t have a Windows-on-ARM machine to play around with to see if it can be made to work.
