### ISSUE TITLE
Pi-hole error on installation

### ISSUE THREAD

**Issue by WatchmanG75** [DesktopECHO/Pi-Hole-for-WSL1#52]
Hi
Thank you for this application
Please assist, as I get errors on installing it in Windows 10
Please see attached screenshots 
![github_error2](https://user-images.githubusercontent.com/102303374/159928246-f0b093c4-a2c4-4add-917d-a76f317fcf4a.png)
![github_error](https://user-images.githubusercontent.com/102303374/159928255-0a7ee73e-f55a-450e-b516-9a4fab77c6e4.png)
Kind regards

**Comment by DesktopECHO** [comment]
Hi there, I think there may be a bug with drive letter handling.  

I see you are specifying E:\ for your install target -- Can you please try installing to C:\ and see if that resolves the issue?
  
In any case I will try to reproduce the issue, but probably won't be able to get to this 'soon' as I'm away for a few weeks.  Let me know how you progress.  Thanks.

**Comment by WatchmanG75** [comment]
Hi,

Thank you for your response.

I also tried C:\ the default and it did not work either, same issue. I
think it is more of a time out on the slow bits download than anything else.

I ended up loading linux on a oracle vbox and installed the pi-hole for
linux on there an all is working fine

Please close the ticket.

Thank you

Kind Regards,
Gregg Biljon
