### ISSUE TITLE
Error when trying to blacklist domain

### ISSUE THREAD

**Issue by mitch-kazel** [DesktopECHO/Pi-Hole-for-WSL1#53]
Installed and running well on Windows 10 for two days.  But when I try to BLACKLIST a domain I get the following error:

![image](https://user-images.githubusercontent.com/102367796/160130459-f69b52fa-dd6a-45fe-b801-ef851dabdc3f.png)

Thanks very much!

**Comment by DesktopECHO** [comment]
Possibly related to https://github.com/pi-hole/docker-pi-hole/issues/860 
The linked issue discusses Docker, but this could also apply to other containerized distributions of Pi-hole.
I will be investigating further... does the issue for you persist across reboots?

**Comment by mitch-kazel** [comment]
I ended up switching to a raspberrypi installation of Pi-hole.  I appreciate the response.

**Comment by edgd1er** [comment]
I had to use a windows based os to test pihole. I tested it with wsl (ubuntu) to stay as close as possible to a unix system. I had the read only problem at each container's start. Even root was not able to change owner nor the rights.

The solution for me was to add in wsl.conf: options= "metadata"
```
[automount]
options = "metadata"
```
