### ISSUE TITLE
How to cahnge port when installation

### ISSUE THREAD

**Issue by xbec65** [DesktopECHO/Pi-Hole-for-WSL1#57]
Hi,

I am using apache /Xampp for my web server. It already uses Port 80. How can i change the pihole Port (e.x: port 3000) when installation?

**Comment by DesktopECHO** [comment]
When the script is initially launched, it checks if port 80 is available.
It prefers port 80 unless it's already in use, in which case it will use port 60080.

If you want to define your own custom port, you can jump on the Pi-hole instance by running `WSL.EXE -d Pi-hole` then edit/create a file called `/etc/lighttpd/external.conf`

Put`server.port := 8080` in `/etc/lighttpd/external.conf` and the web server will listen on port 8080 moving forward.

**Comment by xbec65** [comment]
Thanks for the reply. Solved it already.
