### ISSUE TITLE
Issue when making custom config

### ISSUE THREAD

**Issue by ItzDragonFace** [DesktopECHO/Pi-Hole-for-WSL1#59]
When writing a custom config and restarting the dns server, PiHole prompts "Permission Denied" for the folder. After heavy investigation, it looks like the whole rootfs folder doesn't give root access permission somehow? This needs fixed badly.

**Comment by ItzDragonFace** [comment]
(I even tried running the Pi-Hole Launcher as admin, it still didn't have enough permission, resulting in an error and closing the program.)

**Comment by ItzDragonFace** [comment]
I'm thinking its an issue dealing with WSL But I'm not sure what it could be, if anyone finds out please let me know.

**Comment by ItzDragonFace** [comment]
UPDATE, after running stat command, It says the custom config file I made has permission of 0000  by DEFAULT (Not even root can access the file). This is a bug and needs fixed.

**Comment by DesktopECHO** [comment]
What do you mean by custom config?  What are the exact steps to reproduce the issue?
