### ISSUE TITLE
curl failed to verify the legitimacy of the server and therefore could not

### ISSUE THREAD

**Issue by Spam-Spamych** [DesktopECHO/Pi-Hole-for-WSL1#6]
Hi! I can't install Pi-hole-for-WSL1.
Installation of "PH4WSL1.cmd" is interrupted at the stage of downloading the installer from the "GitHub" site. 

---- ERROR
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: `https://curl.haxx.se/docs/sslcerts.html`

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
---- ERROR

If I run this command separately  everything goes fine:
`curl -L https://install.Pi-hole.net`
The file "curl.exe" is in my "system32" directory.

Pi-hole for Windows
-------------------

Location of "Pi-hole" folder [Default = C:\Program Files]
Response: c:\pi-hole

Pi-hole listener IP and subnet in CIDR format, ie: 192.168.1.99/24
Response: 192.168.178.20/24

Port for Pi-hole. Port 80 is good if you don't have a webserver, or hit enter for default [8880]:
Response:

Install to: c:\pi-hole\Pi-hole
   Network: 192.168.178.20/24
      Port: 8880

Fetching LxRunOffline...

Installing Ubuntu 20.04...

Shrinking footprint...

Installing dependencies...
Extracting templates from packages: 100%

Launching Pi-hole installer...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

Web Interface Admin
/bin/bash: pihole: command not found
---------------------------------------------------------------------------
ERFOLGREICH: Die geplante Aufgabe "Pi-hole for Windows" wurde erfolgreich erstellt.
Drücken Sie eine beliebige Taste . . .
Pi-hole for Windows Installed to c:\pi-hole\Pi-hole

c:\pi-hole\Pi-hole>

**Comment by DesktopECHO** [comment]
Hi there,

What version of Windows are you running?  Windows 10 should not exhibit this problem.

Thanks,
D.

**Comment by DesktopECHO** [comment]
Also, see:

https://www.reddit.com/r/pihole/comments/996ho5/unable_to_install_pihole_curl_60_ssl_certificate/

**Comment by Spam-Spamych** [comment]
> 
> 
> One other thing to try...
> 
> Uninstall the failed instance then
> On line 59 of the script, change:
> 
> `%GO% "curl -L https://install.Pi-hole.net | bash /dev/stdin --unattended"`
> 
> to
> 
> `%GO% "curl -k -L https://install.Pi-hole.net | bash /dev/stdin --unattended"`
> 
> That being said, you should't have to force skipping certificate checks.

yes. that resolved my problem. but FTL can't install - same problem:

```
  [i] FTL Checks...

  [✓] Detected x86_64 architecture
  [i] Checking for existing FTL binary...
  [i] Downloading and Installing FTL...curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
  [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-linux-x86_64 not found
  [✗] FTL Engine not installed
```

> What version of Windows are you running? Windows 10 should not exhibit this problem.

```
Betriebssystemname:                            Microsoft Windows 10 Pro
Betriebssystemversion:                         10.0.19041 Nicht zutreffend Build 19041
Betriebssystemhersteller:                      Microsoft Corporation
Betriebssystemkonfiguration:                   Eigenständige Arbeitsstation
Betriebssystem-Buildtyp:                       Multiprocessor Free
Systemtyp:                                     x64-based PC
```

> Do you know if you are you on a corporate network that has packet inspection?

i'm not in corporate network but in private.

> Also, see:

ok. I will read

**Comment by DesktopECHO** [comment]
Perhaps you had a download failure during the install.  If you're not too invested, just wipe it out with Pi-hole_Uninstall.cmd and re-run the script.

**Comment by DesktopECHO** [comment]
If you don't want to do that, run wsl.exe and type ```update-ca-certificates```
Then re-run ```Pi-hole_Reconfigure.cmd``

**Comment by Spam-Spamych** [comment]
> Perhaps you had a download failure during the install. If you're not too invested, just wipe it out with Pi-hole_Uninstall.cmd and re-run the script.

It's worked!
Thanks a lot!
**And i have changed a install directory to "c:\\"**

I've used reinstallation many times, but all the time in the same directory. 
It may have crashed because the directory name was "c: \ pi-hole \"

Thanks!
