### ISSUE TITLE
Configuration cmd file not present?

### ISSUE THREAD

**Issue by Thiefsie** [DesktopECHO/Pi-Hole-for-WSL1#60]
My install is missing this file?

The VM has erroneously attached to the wrong network interface and I need to change it somehow...:
![WSL](https://user-images.githubusercontent.com/45855407/172415291-499a70c4-d7cd-415b-805a-7998216d80e5.JPG)
.

**Comment by DesktopECHO** [comment]
To run Pi-hole Reconfigure you can open a command prompt (CMD.EXE) and run:
`"C:\Program Files\Pi-hole\LxRunOffline.exe" r -n Pi-hole -c  "PIHOLE_SKIP_OS_CHECK=true pihole reconfigure"`

If you're missing this file I'd be concerned other parts of the install were deletd too.  Consider uninstalling an reinstalling Pi-hole to be sure.

**Comment by Thiefsie** [comment]
OK Thanks, I got in from powershell and just ran -r and got it cleaned up.

As you suggest I'll fully reinstall to make sure it's clean.
