### ISSUE TITLE
PowerShell Issue

### ISSUE THREAD

**Issue by opus-x** [DesktopECHO/Pi-Hole-for-WSL1#61]
This didn't work for me out of the box. On my system (W11) powershell.exe is hard linked to powershell_copy.exe which causes the script to open infinite PowerShell windows since powershell.exe is invoked but immediately exits. The batch loop then reinvokes  powershell.exe. I had to change POWERSHELL.EXE in the script to POWERSHELL_COPY.EXE and it worked.

**Comment by DesktopECHO** [comment]
Good to hear you got it working.  

Not sure how to prevent that loop from happening in situations like yours, where POWERSHELL.EXE has been moved out of it's expected location.
