### ISSUE TITLE
Error modifying task in Task Scheduler

### ISSUE THREAD

**Issue by Kraxis78** [DesktopECHO/Pi-Hole-for-WSL1#62]
After installation, I tried to adjust the settings in the scheduled task as the instructions indicated and I get the following error when I try to save/hit OK:

"An error has occurred for task Pi-hole for Windows. Error message: The following error was reported: The task XML contains a value which is incorrectly formatted or out of range.

This is on Windows 10 20H2

**Comment by DesktopECHO** [comment]
Hi.. that's odd, can you post a screenshot when this occurs?
Thanks.

**Comment by Kraxis78** [comment]
This happens right after I click OK to save the changes to the task. It doesn't matter if I even change anything. I can go into the task properties and immediately just hit OK and it comes up with that error.

![Task Scheduler PiHole error](https://user-images.githubusercontent.com/108959299/178087255-0c31ac4e-f746-4a9c-b3df-18e86a463419.png)

**Comment by DesktopECHO** [comment]
Try deleting the scheduled task:

`SCHTASKS /Delete /TN:"Pi-hole for Windows"`

...and re-create it:

`SCHTASKS /CREATE /RU SHENRON\mydomainusername /RL HIGHEST /SC ONSTART /TN "Pi-hole for Windows" /TR 'C:\Program Files\Pi-hole Launcher.cmd'`

Then try editing the Scheduled Task again.

**Comment by Kraxis78** [comment]
Same result/error.
![Pihole2](https://user-images.githubusercontent.com/108959299/178089111-142def73-c4ea-4666-ad60-5e1a1db01e9f.png)

**Comment by DesktopECHO** [comment]
Strange... First I've heard of this issue with Task Scheduler but there are a few other [rumblings online](https://www.google.com/search?q=%22task+xml+contains+a+value%22&biw=1407&bih=899&tbs=qdr%3Am&ei=xO_IYueMINGv5NoP2vKTYA&ved=0ahUKEwjn_sHk6Or4AhXRF1kFHVr5BAwQ4dUDCA4&uact=5&oq=%22task+xml+contains+a+value%22&gs_lcp=Cgdnd3Mtd2l6EAMyBwgAEEcQsAMyBwgAEEcQsANKBAhBGABKBAhGGABQAFgAYIEEaAFwAHgAgAEAiAEAkgEAmAEAyAECwAEB&sclient=gws-wiz)

There's nothing really special about this Scheduled Task.  Try deleting it again and manually re-create in the Scheduled Tasks GUI.

**Comment by Kraxis78** [comment]
Well, turns out I have a Windows issue and not an app/Pi-Hole issue.. I could modify NO tasks..  I should have checked that as my seconds step...
