### ISSUE TITLE
Just a question, can this be installed on a secondary hdd

### ISSUE THREAD

**Issue by vmdyap2022** [DesktopECHO/Pi-Hole-for-WSL1#65]
Hi, this is not an issue but more of curiosity question.

Can I install this on a secondary hdd instead? I'm asking incase I dont have enough storage space on the main drive. Ty

**Comment by DesktopECHO** [comment]
Hi you can install to a different drive without issue.  

I wasn't 100% on that question so I verified a successful install to another driver letter on a lab machine (A:\ in my case) -- No problems seen as long as your disk is NTFS formatted.

**Comment by vmdyap2022** [comment]
Thank you for the reply. This really help a lot.
