### ISSUE TITLE
Script Hangs on Downloading Debian Image

### ISSUE THREAD

**Issue by ForbodingAngel** [DesktopECHO/Pi-Hole-for-WSL1#66]
I've run into this before, and last time I was able to solve it, but I can't remember for the life of me what I did to fix it.

![2022-09-29 01_12_39-Greenshot](https://user-images.githubusercontent.com/369586/192977570-a83b5a37-1c49-4feb-9263-27d088e44cb7.png)

Here it is hopelessly hung. So, opening it up in an editor, I see that it is getting stuck on this line:

`POWERSHELL.EXE -Command "Start-BitsTransfer -Source https://salsa.debian.org/debian/WSL/-/raw/master/x64/install.tar.gz -Destination '%TEMP%\%IMG%'" >NUL 2>&1`

So, I check it out in powershell and this is the result:
![2022-09-29 01_17_37-Window](https://user-images.githubusercontent.com/369586/192978586-e8ca4957-0b2d-4f6e-87d5-c370b61a94b4.png)

At this point I just don't know where to go from here. Last time I ran into this I was able to modify the script and get it to work but I can't remember what I did /facepalm

**Comment by ForbodingAngel** [comment]
Path is nothing special `C:\Users\Server\AppData\Local`

Permissions are standard. Administrators group has full control, as well as the user "Server", as well as System. As an interesting test, I added everyone and game it full permissions but still no dice. It seems like maybe it's an issue with the bitstransfer?

As a side note, I'm tempted to sub it out for a wget command and see if that's less of an issue. Is it possible that a windows feature is disabled that is necessary? I guess I could just get around it by manually putting the file there and bypassing this command, but this is the second time I've run into this issue and I want to have it documented what the fix is, because I highly doubt that I am the first one to run into it.

**Comment by DesktopECHO** [comment]
I cant reproduce the issue but try this line instead:

`POWERSHELL.EXE -Command "Start-BitsTransfer -Source https://salsa.debian.org/debian/WSL/-/raw/master/x64/install.tar.gz -Destination '%TEMP%\Debian.tar.gz'"`

**Comment by ForbodingAngel** [comment]
So I've spent a bunch of time trying to figure out where this is going sideways. So I grew a partial brain and started echoing dlimg. Perhaps this should have a retry counter. Because with echo off it just appears to hang while in the background it's just spamming the command in a loop.

![image](https://user-images.githubusercontent.com/369586/193121421-1b1a51fe-ffc1-4518-a461-6ce4a66d6816.png)

**Comment by ForbodingAngel** [comment]
Ok so that command illuminated things a bit for me:

![image](https://user-images.githubusercontent.com/369586/193122350-10bd2de8-1152-4d8c-a30a-d5b658add0cc.png)

Interestingly, it seems that something with the check is not happening properly. In the meantime, I'm going to do a network reset (this is not an important server atm), on it and see if that makes it happier.

**Comment by ForbodingAngel** [comment]
I solved it. This happens when windows probes for internet get all screwed up. So thankfully, someone else had figured this out before me which saved me a ton of time. I will link to the answers page but also post the content here for posterity.

[https://answers.microsoft.com/en-us/windows/forum/all/windows-shows-no-internet-access-but-my-internet/2e9b593f-c31c-4448-b5d9-6e6b2bd8560c](url)

`Kapil Arya MVP

   [ MVP ](http://answers.microsoft.com/en-us/page/faq#faqWhosWho1)|
    Volunteer Moderator`
    
`1. Press Windows + R keys.

2. Type regedit, click OK.

3. Go to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet.

4. Make sure following values exist in right pane of Internet:

"ActiveDnsProbeContent"="8.8.4.4"

"ActiveDnsProbeContentV6"="2001:4860:4860::8844"

"ActiveDnsProbeHost"="dns.google"

"ActiveDnsProbeHostV6"="dns.google"

"ActiveWebProbeHostV6"="www.msftconnecttest.com"

"EnableActiveProbing"="1"

5. Restart your Computer or disable/enable your connection and reboot your router.

If you need more help with above mentioned steps, check this video:

https://www.youtube.com/watch?v=v3CkXHgj6Ig`

@DesktopECHO thank you for your help and pointing me in the right direction. Hopefully this saves someone else a headache on down the line.

**Comment by DesktopECHO** [comment]
Glad to hear you're sorted, all the best!
