### ISSUE TITLE
Pi-Hole blocking Internet access (apparently?)

### ISSUE THREAD

**Issue by gyrorayo** [DesktopECHO/Pi-Hole-for-WSL1#67]
Hi, I've been using Pi-Hole in my Linux partition for the last 3 months or so. Thank you so much for enabling us to use on Windows too!

Everything's been working fine as far as I know, however, I have noticed some "odd" behavior lately. PHWSL1 apparently is blocking every site I try to visit, if I don't have an active Internet connection before Windows login. I mean, I have to either enable "Connect automatically" for WiFi connections or have an ethernet cable attached to my laptop. 

I don't really know if I have to provide a log or something like that, but I "feel" this is a Windows bug, I am by no means an expert. 

currently I'm using Windows 11 Pro, btw

**Comment by DesktopECHO** [comment]
Hi, try adding the following custom DNS entries for Windows networking probe:

![image](https://user-images.githubusercontent.com/33142753/193875409-95f467ba-aa6d-414a-b479-371f33a06b49.png)

Let me know if this helps your situation.
Thanks.
D.

**Comment by gyrorayo** [comment]
Hi, thanks for the reply. I did as you instructed, but the problem persists. And just now I'm noticing that it happens even with ethernet attached, furthermore, it's not only visiting pages, but every connection is blocked (steam, windows update...)

I have to disable pi-hole by setting get DNS server automatically if I want to use internet again. 

- re enabled it after a while and started working properly again... is it my computer that has a problem?
Thanks in advance.

**Comment by DesktopECHO** [comment]
What's your PowerShell output from:

`reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet" -v ActiveWebProbeHost`

On my machine it's:

    ActiveWebProbeHost    REG_SZ    www.msftconnecttest.com
