### ISSUE TITLE
Pihole not installing correctly

### ISSUE THREAD

**Issue by swaggyboi** [DesktopECHO/Pi-Hole-for-WSL1#68]
![image](https://user-images.githubusercontent.com/70466886/194789163-2647cde0-69cb-4334-a5fa-62d498580b8c.png)
Its prob something im doing wrong but i dont get why its not installing correctly.  When I continue with the installation it closes and attempts to run the site but it says it cant be reached.

**Comment by DesktopECHO** [comment]
I see something weird... your IP and interface info aren't being picked up, like so:
![image](https://user-images.githubusercontent.com/33142753/194790707-c8537a4b-98f6-4c7a-8251-c080757e6a59.png)
- If you are from a region with restricted Internet access, try changing the discovery beacon on line 63 and 64 from Quad9 to something closer to home.
- If you have 2 NICs try disabling one, then uninstall/reinstall. 
- Out of other ideas for the moment... that detection code hasn't been messed-with in ages and it has always worked great!

**Comment by swaggyboi** [comment]
> 

I live in the US, there should be no restrictions here.  Tried disabling an NIC and didn't work.  Thank you for the suggestions tho!

**Comment by swaggyboi** [comment]
> I see something weird... your IP and interface info aren't being picked up, like so: ![image](https://user-images.githubusercontent.com/33142753/194790707-c8537a4b-98f6-4c7a-8251-c080757e6a59.png)
> 
> * If you are from a region with restricted Internet access, try changing the discovery beacon on line 63 and 64 from Quad9 to something closer to home.
> * If you have 2 NICs try disabling one, then uninstall/reinstall.
> * Out of other ideas for the moment... that detection code hasn't been messed-with in ages and it has always worked great!

Hey so I tried installing pihole on an older computer running the same OS i have on this, (windows 10) and i encountered the same issue.  Is it something with my router?

**Comment by DesktopECHO** [comment]
Certainly sounds that way...  Try this:  
Change lines 63 and 64 of `PH4WSL1.CMD` from `9.9.9.9` to the IP of your router.   
Un-install and re-run the modified script.

**Comment by swaggyboi** [comment]
> Certainly sounds that way... Try this: Change lines 63 and 64 of `PH4WSL1.CMD` from `9.9.9.9` to the IP of your router. Un-install and re-run the modified script.

Tried and got the same results, is there anything else i could try?  Thank you for your help up until now btw.

**Comment by DesktopECHO** [comment]
Just tried on a test machine to be sure.... no issues.

![image](https://user-images.githubusercontent.com/33142753/194805004-02e99396-55be-46c2-9fa6-7a3d173d5f65.png)

Try this:  Line 67 and 68 are as follows:
`%GO% "echo IPV4_ADDRESS=%IPC%          >> /etc/pihole/setupVars.conf"`
`%GO% "echo PIHOLE_INTERFACE=%IPF%      >> /etc/pihole/setupVars.conf"`

Enter your machine's IP, for my example it's `192.168.0.10` Change it like so:
`%GO% "echo IPV4_ADDRESS=192.168.0.10/24  >> /etc/pihole/setupVars.conf"`
`%GO% "echo PIHOLE_INTERFACE=eth0 >> /etc/pihole/setupVars.conf"`

...Then uninstall and re-run the modified script.

If that doesn't work, only other thing I can suggest for the moment is to run the "Reconfigure" utility here:
`C:\Program Files\Pi-hole\Pi-hole Configuration.cmd`

**Comment by DesktopECHO** [comment]
Open a command prompt and run:
`wsl -d Pi-hole`
Then run the interface detection lines manually:

`IPC=$(ip route get 9.9.9.9 | grep -oP 'src \K\S+') ; IPC=$(ip -o addr show | grep $IPC) ; echo $IPC | sed 's/.*inet //g' | sed 's/\s.*$//'`

`IPF=$(ip route get 9.9.9.9 | grep -oP 'src \K\S+') ; IPF=$(ip -o addr show | grep $IPF) ; echo $IPF | sed 's/.*: //g'    | sed 's/\s.*$//'`

...and let me know the output.

**Comment by swaggyboi** [comment]
![image](https://user-images.githubusercontent.com/70466886/194966611-9fbce8c3-75b5-4882-808a-cdfc6519191d.png) am 99% sure im doing something wrong

**Comment by DesktopECHO** [comment]
Are you able to set WSL1 as default:
`wsl --set-default-version 1`

Then try to install Debian from the Microsoft store.
[https://apps.microsoft.com/store/detail/debian/9MSVKQC78PK6](https://apps.microsoft.com/store/detail/debian/9MSVKQC78PK6)

Then in Debian try interface detection:
`IPC=$(ip route get 9.9.9.9 | grep -oP 'src \K\S+') ; IPC=$(ip -o addr show | grep $IPC) ; echo $IPC | sed 's/.*inet //g' | sed 's/\s.*$//'`

`IPF=$(ip route get 9.9.9.9 | grep -oP 'src \K\S+') ; IPF=$(ip -o addr show | grep $IPF) ; echo $IPF | sed 's/.*: //g' | sed 's/\s.*$//'`

**Comment by swaggyboi** [comment]
> That worked. Ok, try to download and run the script from the repo:
> 
> `PowerShell -c "Invoke-Webrequest https://raw.githubusercontent.com/DesktopECHO/Pi-Hole-for-WSL1/master/PH4WSL1.cmd -OutFile PH4WSL1.cmd ; .\PH4WSL1.CMD"`
> 
> Any luck?

no luck
![image](https://user-images.githubusercontent.com/70466886/195462503-06fddc9b-ba63-4fc7-8346-24eb2b7cb985.png)

**Comment by DesktopECHO** [comment]
What's the output from:
`CMD /C VER`
and 
`wslconfig /l`
and 
`wsl -d Pi-hole`

**Comment by swaggyboi** [comment]
![image](https://user-images.githubusercontent.com/70466886/195481546-84654787-33b1-4a81-bb52-b74a9afe3d9f.png)

**Comment by DesktopECHO** [comment]
That is so weird... your machine tells us Pi-hole is installed.  
But you try to access it, and it says it can't find it.  

What does LXrunOffline make of this mess?  What's the output from:
`CMD /C  "C:\Program Files\Pi-hole\LxRunOffline.exe" r -n Pi-hole`

**Comment by swaggyboi** [comment]
huhhhhh
![image](https://user-images.githubusercontent.com/70466886/195483848-cea69e28-1281-402f-9ec1-6848a1be691b.png)

**Comment by DesktopECHO** [comment]
Wow.  That is... not what I was expecting.  
Sorry no idea what's happening here...

**Comment by swaggyboi** [comment]
> Just for fun you can try uninstalling the instance in `C:\Program Files` and install to `C:` (It will install to `C:\Pi-hole`) May work, but there is still something wrong with your OS by the looks of it.

I'm running windows 10 Home and tried it with an older computer that uses win 10 home as well

**Comment by DesktopECHO** [comment]
Uninstall the existing instance in `C:\Program Files` and install to `C:\` instead. 
Then you can try:
`CMD /C "C:\Pi-hole\LxRunOffline.exe" r -n Pi-hole`

**Comment by DesktopECHO** [comment]
Also, verify that LongPathsEnabled =1 

` PowerShell -c 'Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled"'`

**Comment by swaggyboi** [comment]
> Also, verify that LongPathsEnabled =1
> 
> ` PowerShell -c 'Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled"'`

LongPathEnables = 0 for some reason
![image](https://user-images.githubusercontent.com/70466886/195526643-00a6fdcd-3a85-4991-a096-9ab4e8a7b21e.png)

**Comment by DesktopECHO** [comment]
Are these machines 'clean' Windows 10 Home installs?  As opposed to upgraded from Windows 7/8

You can also try installing to `C:\ProgramData` instead of `C:\Program Files` to see if it's the space character causing the issue.

**Comment by swaggyboi** [comment]
> C:\ProgramData

Downgraded from Win 11 on this computer and other computer has been on win 10 only

**Comment by DesktopECHO** [comment]
Did you try installing to `C:\ProgramData` or `C:\` and if so what was the outcome?

**Comment by swaggyboi** [comment]
> Did you try installing to `C:\ProgramData` or `C:\` and if so what was the outcome?
![image](https://user-images.githubusercontent.com/70466886/195655461-874db42c-a376-4f3e-8f51-becde0079f1d.png)

:/

**Comment by swaggyboi** [comment]
![image](https://user-images.githubusercontent.com/70466886/195714681-ff982c4b-7358-4769-a055-148094404542.png)
Tried C: came out the same way

**Comment by DesktopECHO** [comment]
Sorry mate, not sure what else I can recommend.

I downloaded the Windows Meda Creator and made a Windows 10 ISO.
Just a few moments ago I did a clean install to a virtual machine -- **No issues**

![image](https://user-images.githubusercontent.com/33142753/195725166-a59f105f-4576-4642-b71a-ec4072165522.png)

I think you'll need a clean install as well.

**Comment by swaggyboi** [comment]
> Sorry mate, not sure what else I can recommend.
> 
> I downloaded the Windows Meda Creator and made a Windows 10 ISO. Just a few moments ago I did a clean install to a virtual machine -- **No issues**
> 
> ![image](https://user-images.githubusercontent.com/33142753/195725166-a59f105f-4576-4642-b71a-ec4072165522.png)
> 
> I think you'll need a clean install as well.

Okay what the fuck it works now that i have a VM lol
![image](https://user-images.githubusercontent.com/70466886/195731982-f6d8f085-b30b-4511-a88f-1b6db3128be5.png)

**Comment by DesktopECHO** [comment]
Cool!
This kind of re-affirms that something is screwy with your existing Windows 10 instal(s)

**Comment by swaggyboi** [comment]
> 

Thank you so much for bearing with my stupidity lol
