### ISSUE TITLE
Revert all changes of script.

### ISSUE THREAD

**Issue by lproto** [DesktopECHO/Pi-Hole-for-WSL1#7]
Hi, is there a way to revert all changes the script made? Once I ran it, I had no internet access and am unable to resolve the internet access issue with the built in Windows troubleshooter or looking at network adapters and seeing any obvious issues there.

**Comment by DesktopECHO** [comment]
Hello, the uninstaller will thoroughly remove the Pi-hole installation.

There's **absolutely nothing** in the script that makes changes to your Windows box other than installing WSL1 if its not already there.  Once Pi-hole is installed you have to set your NIC's DNS server to point at it.

Can you ping 8.8.8.8?

If you type nslookup from a command prompt, what is your machine's reply?

**Comment by lproto** [comment]
Hi,
Pinging 8.8.8.8 returns, "General failure."

Nslookup returns:
Default Server: Unknown
Address: 192.168.86.1

**Comment by lproto** [comment]
I now see I am unable to ping 192.168.86.1

**Comment by DesktopECHO** [comment]
What are the contents of ipconfig? (Please redact your DNS suffix and any other personally identifiable information you see)

**Comment by lproto** [comment]
For the only device that doesn't say "Media disconnected, 
Connection-specific DNS suffix: lan 
Link-local IPv6 Address: redact this too right?
IPv4 Address: 192.168.86.34
Subnet Mask: 255.255.255.0
Default Gateway: 192.168.86.1 (which I can ping now)

One very interesting thing I just discovered: I can connect to my VPN (IKeV2) and connect to the internet that way...

**Comment by lproto** [comment]
Wait a second now that I turned my VPN off I can connect to the internet fine now..

**Comment by DesktopECHO** [comment]
Is an adaptor disabled in your device manager?
[microsoft/WSL#5153](https://github.com/microsoft/WSL/issues/5153)

Your issue is not so much the PH install script, but a WSL1 interaction with a VPN/TUN adaptor.  Have you rebooted your machine?  

You can remove WSL by going to Control Panel -> Programs and Features -> Turn Windows Features On or Off

**Comment by lproto** [comment]
Yes I believe that must've been the issue (no longer an issue since turning on the VPN once seems to have re-enabled whatever adapter was disabled causing the issue).

**Comment by lproto** [comment]
So I'd say issue resolved.

**Comment by DesktopECHO** [comment]
Ok I missed one of your updates.  Looks like you're back up and running, correct?
You can give the Pi-hole installer another spin if you like, now that we know why your networking was misbehaving.
