### ISSUE TITLE
Request: Kindly add guide on how to update pi-hole

### ISSUE THREAD

**Issue by vmdyap2022** [DesktopECHO/Pi-Hole-for-WSL1#71]
Hi, this is not an issue but a request to add an instruction how to update pi-hole. 

I had to check closed issues to find the answer to this and I think it is better if it is in the main page too. 

Thank you for your hard work,

**Comment by DesktopECHO** [comment]
Hi there - Fair point, these options should be made more obvious.

![image](https://user-images.githubusercontent.com/33142753/196202842-1003d4a9-508a-4bf4-86e0-447414fa8f60.png)

Hope that helps!
D.

**Comment by vmdyap2022** [comment]
> Hi there - Fair point, these options should be made more obvious.
> 
> ![image](https://user-images.githubusercontent.com/33142753/196202842-1003d4a9-508a-4bf4-86e0-447414fa8f60.png)
> 
> Hope that helps! D.

Thank you that helps, sorry 1 more thing, it will be better if a little note on how to upgrade pi-hole in general like for ex, run system update then run configuration after or if we all need to run all 3 commands. Again ty for this.

**Comment by DesktopECHO** [comment]
Hello, I added hyperlinks to additional information.

![image](https://user-images.githubusercontent.com/33142753/197323331-320ceef0-3d40-44fe-9661-e0f4d24131f6.png)
