### ISSUE TITLE
Since updating to 22H2, pihole doesn't autostart 

### ISSUE THREAD

**Issue by seanbperiod** [DesktopECHO/Pi-Hole-for-WSL1#74]
I have it set in task scheduler but it still doesn't seem to autostart, and I have to manually start it..

What's the best way to reset this.. just reinstall pihole?

**Comment by DesktopECHO** [comment]
You can do a re-install or try this first:

Try deleting the scheduled task:

`SCHTASKS /Delete /TN:"Pi-hole for Windows"`

...and re-create it:

`SCHTASKS /CREATE /RU SHENRON\mydomainusername /RL HIGHEST /SC ONSTART /TN "Pi-hole for Windows" /TR 'C:\Program Files\Pi-hole Launcher.cmd'`

Then:
- Open Windows Task Scheduler (taskschd.msc) and right-click the Pi-hole for Windows task, click edit.
- On the General tab, place a checkmark next to both Run whether user is logged on or not and Hidden
- On the Conditions tab, un-check the option Start the task only if the computer is on AC power

Then enter your password and see if it sticks.
Also woith mentioning your account needs a login password set (no blank passwords allowed)

**Comment by DesktopECHO** [comment]
You may also need [KB5018496](https://support.microsoft.com/en-us/topic/october-25-2022-kb5018496-os-build-22621-755-preview-64040bea-1e02-4b6d-bad1-b036200c2cb3)

**Comment by seanbperiod** [comment]
Thanks! 

Already have KB5018496 installed. 

After the second command, I got: 
ERROR: No mapping between account names and security IDs was done.

I assume I need to replace mydomainusername? but I tried entering my Windows user name, but I got the same error.

**Comment by DesktopECHO** [comment]
Yeah it looks like it's not recognizing your username; I was able to re-create this by using a bad username and then retrying it works with a valid user -- See below:

![image](https://user-images.githubusercontent.com/33142753/198357088-29e5a447-9c17-4abd-b02a-d4bc2b563c79.png)

**Comment by seanbperiod** [comment]
Got it 👍

Just restarted, and it's still not auto-running. 

https://share.seanburdick.com/jkuWkO1O

Shall I try uninstall/reinstall? Any other way to diagnose?

**Comment by DesktopECHO** [comment]
You can uninstall/reinstall.. but I suspect you'll have the same issue, unless the Pi-hole installation is messed up as well.  

Does Pi-hole run manually when you open Pi-hole Launcher? (It's in the install folder)

Maybe try creating your own scheduled task and see if that runs, to determine if it's an issue with Windows in general or specific to this Pi-hole install.

**Comment by seanbperiod** [comment]
Yes, I'm able to run it from the Launcher fine. 

One thing I noticed is that it was trying to Launch directly from the Program Files directory, and not the Pi-Hole directory. I updated that, but it still doesn't run at startup. 

I added a new trigger to run at logon, and that seems to be working for the time being. Not really an issue otherwise, but interesting that this happened 🤷‍♂️ 👍

**Comment by DesktopECHO** [comment]
Cool, well that's good to hear at least.  If that suffices for you then all's well, just means no Pi-hole until you're logged-in.
 
Will def keep an eye open for other reports like this... my 22H2 boxes aren't seeing this issue but they're not upgrades from 22H1.

**Comment by seanbperiod** [comment]
I appreciate the help! And thanks for making this to begin with 👍 :)

**Comment by ichxorya** [comment]
I have tried to make it start after failure, and add more 5 tries if fail. It works for me!
