### ISSUE TITLE
Getting [PHP error (2): fsockopen() unable to connect to 127.0.0.1:4711 after installing on a different system

### ISSUE THREAD

**Issue by vmdyap2022** [DesktopECHO/Pi-Hole-for-WSL1#75]
Hi, sorry I'm bothering you again,
I wanted to move the pihole server to a different windows system, still using windows 10 and it is fully updated.
but when I go to the setting its give me an error: "[PHP error (2): fsockopen(): unable to connect to 127.0.0.1:4711 (Connection refused)](https://discourse.pi-hole.net/t/php-error-2-fsockopen-unable-to-connect-to-127-0-0-1-4711-connection-refused/55534) in /var/www/html/admin/scripts/pi-hole/php/FTL.php:47"

firewall and av are off.

update: found the log: https://pastebin.com/GjhE2h7N

ty for any help.

**Comment by DesktopECHO** [comment]
Have you tried uninstalling and reinstalling?  I can't replicate the issue.

Were you trying to install additional blocklists?  If so, was Pi-hole working before attempting to do so?

**Comment by vmdyap2022** [comment]
> Have you tried uninstalling and reinstalling? I can't replicate the issue.
> 
> Were you trying to install additional blocklists? If so, was Pi-hole working before attempting to do so?

I tried reinstalling it 3x, and getting same error, I cant update gravity because of the said error. 

I'm not sure if this is conflicting with my jellyfin server but that one uses port 8090

**Comment by vmdyap2022** [comment]
HI, i'm really sorry, forgot one step when t/s, redownloading the bat file again. After installing it, it now works. Again im sorry to have bothered you.
