### ISSUE TITLE
DNS will not resolve on anything besides host server

### ISSUE THREAD

**Issue by slunat** [DesktopECHO/Pi-Hole-for-WSL1#76]
I previously was running pihole just fine through this script on my machine. I then started a fresh Windows install after changing hard drives so had to reinstall Pihole, ever since doing so I have not been able to get Pihole to be fully functional. It works perfectly fine on my host server that is running Pihole and ad requests are getting blocked, as well as normal traffic working fine. However, on any other devices on my network, Pihole does not work. None of my DNS results will resolve so nothing loads at all.

I have tried:
Reinstalling Pihole
Disabling Windows Defender Firewall
Disabling Firewall and then reinstalling Pihole
Restoring my old config from my previous install
Trying a completely fresh config with none of my previous settings
Disabled IPV6 on all network interfaces
Unchecking the two "Never Forward" options under Advanced DNS settings

Permit All Origins is enabled.

The strange thing is, from the Pihole dashboard everything looks fine. I can see the incoming requests there from my devices I have connected to it and it shows both OK and blocked DNS results, but its like it is failing to send the packets back to the device as nothing ever resolves.

The client in the image below is my iphone, none of those connections work. Despite all those OK Netflix requests, it does not load.

![image](https://user-images.githubusercontent.com/24834294/201779294-8cc04175-10c2-410a-ab56-45dfef0d7562.png)

**Comment by DesktopECHO** [comment]
I assume `192.168.10.31` is where your Pi-hole is installed, right?

If so, goto one of the other PC's on your network and confirm their DNS settings are correct by opening a PowerShell console and running `ipconfig /all | find "DNS Servers"`  

They should come back with the IP of your new DNS server (in the case assumed above,  `192.168.10.31` )

When you did a fresh install, did you keep the same IP address for your Windows box?

**Comment by slunat** [comment]
Sorry I should've mentioned, my host Windows machine IP is 192.168.10.10, which works fine going through Pihole.

192.168.10.31 is my iPhone, but nothing will load even though it all looks OK on Pihole. I manually set the DNS server in my wifi settings on the phone so it is definitely using that Pihole. If I switch the DNS to something else like 8.8.8.8 everything loads fine, the second I switch it to my Pihole which is 192.168.10.10, nothing loads.
I have tried running the command on another Windows machine and I can confirm it shows my Pihole server as the DNS.
![image](https://user-images.githubusercontent.com/24834294/201949589-c2c064f5-b6b4-45b3-be5a-3e9d13ac415d.png)

I did keep the same IP with my fresh install, I have that IP set in my DHCP reservations on my router.

**Comment by DesktopECHO** [comment]
Try uninstalling and re-installing Pi-hole (there is an uninstaller in the program folder, run as admin)

Now that we know we're back to a 'stock' configuration, go to another Windows machine on your network and open a Command Prompt and run:

`nslookup google.com 192.168.10.10`

What's the output from the command?

**Comment by slunat** [comment]
I have reinstalled Pihole and run the command from a second machine, please see below output.

![image](https://user-images.githubusercontent.com/24834294/201963227-2a11efb5-8b97-4ada-a92f-803c7dcdbe29.png)

**Comment by DesktopECHO** [comment]
What do you have for antivirus, Windows Defender or something else?

**Comment by slunat** [comment]
Only Windows Defender. I have even tried fully disabling it but it doesnt make a difference.

**Comment by DesktopECHO** [comment]
On the Windows host running Pi-hole, please run
`nslookup google.com 192.168.10.10`
And
`nslookup google.com 127.0.0.1`

**Comment by slunat** [comment]
![image](https://user-images.githubusercontent.com/24834294/201964857-4312b5f6-016f-4887-a087-2605c8be810e.png)

**Comment by slunat** [comment]
On the same WIndows host as Pihole, I'm running docker for Windows.

**Comment by DesktopECHO** [comment]
Did your previously-working setup also have Docker?  
Can you shut down your Docker services and/or any other instances on your machine and restart Pi-hole?  It seems like Docker is in the way.   Lots of interesting [stuff online. ](https://www.google.com/search?q=docker+windows+port+53)

**Comment by slunat** [comment]
I did have Docker on my previous install, I did reinstall Docker at several points though so I'm not sure if Docker was currently installed when I installed Pihole on my previous install or if I had installed Pihole before reinstalling Docker.

I shut Docker down and restarted Pihole. I re-ran the nslookup from the server host and it changed to the below. Still no response on other devices though unfortunately.

![image](https://user-images.githubusercontent.com/24834294/201977024-8df72c3e-7f93-4a0b-9303-b1e013bf095d.png)

**Comment by DesktopECHO** [comment]
Try this:

`netsh interface portproxy add v4tov4 listenaddress=192.168.10.10 listenport=53 connectaddress=127.0.0.1 connectport=53`

If it doesn't help, revert the change with:

`netsh interface portproxy delete v4tov4 listenaddress=192.168.10.10 listenport=53`

**Comment by slunat** [comment]
It didn't make a difference unfortunately. There are no other port proxies in place.

**Comment by DesktopECHO** [comment]
Is the Windows service "Internet Connection Sharing" enabled?  If so disable it and retry.

**Comment by slunat** [comment]
I got it disabled, still no change though unfortunately.

**Comment by DesktopECHO** [comment]
Try restarting your machine and make sure Internet Connection Sharing isn't re-enabled.
Unfortunately the only other thing I can recommend is a clean Windows install.
