### ISSUE TITLE
Memory usage high (vs. Docker)

### ISSUE THREAD

**Issue by matthew-dean** [DesktopECHO/Pi-Hole-for-WSL1#78]
Hi, I'm installing using this script on a Windows 11 mini-PC. Previously, when I set up using the official Docker image, it said that memory usage was ~35%. (I believe it was Docker on WSL2 using Alpine Linux.)

After I've installed using this script, it says memory usage is ~83% in the Admin UI. Should I be concerned with that high number and is there any reason for it?

**Comment by DesktopECHO** [comment]
Hi, actually Pi-hole, when running in WSL1 uses way, way less CPU and RAM than Docker. 

Pi-hole "memory usage" in WSL1 will show the memory use of your native Windows session, there's no separate Linux VM.  In Docker/WSL2 it's reporting free memory of whatever RAM was assigned to the virtual machine running Linux.  Check Task Manager for memory usage when running in Docker, then check again running in WSL1.

You can verify for yourself (or you'll find a rogue process taking up loads of RAM, lol)
Open task manager and sort by "Image Path Name"

Pi-hole -related processes take about _10 megabytes_ of RAM; surprisingly tiny.   
![image](https://user-images.githubusercontent.com/33142753/205808442-acc2715f-ed7e-4390-9913-8c327942b6ea.png)

**Comment by matthew-dean** [comment]
hmm ok
