### ISSUE TITLE
No matter what I do, it won't run on startup?

### ISSUE THREAD

**Issue by matthew-dean** [DesktopECHO/Pi-Hole-for-WSL1#81]
I've followed [the instructions](https://github.com/DesktopECHO/Pi-Hole-for-WSL1#note-1) to startup PiHole on Windows 11 and checked / re-checked settings. In fact, Windows Task Scheduler says it's running.

However, it isn't. If I go into the Pi-Hole Configuration tool and reset or reconfigure pi-hole, then it works again. I double-check it, and yes, the admin interface is now accessible and working with DNS requests locally. However, with every Windows 11 restart, nope, it's dead again.

What am I not thinking of / need to try?

**Comment by matthew-dean** [comment]
Oops, either I wasn't waiting long enough for all startup services or it resolved itself? 🤷‍♂️

**Comment by DesktopECHO** [comment]
Hi @kevin01523 I think you are running into an issue that affects anyone who upgraded to Windows 22H2 from 21H2.  If you search '22h2 Scheduled Task broken' you will invariably be led to [Windows 11 22H2 upgrade breaks "Run whether user is logged on or not" scheduled tasks](https://answers.microsoft.com/en-us/windows/forum/all/windows-11-22h2-upgrade-breaks-run-whether-user-is/3469fd3d-9b89-4d66-b523-501baf57185e) (I jumped into the thread around page 12) but MS has **not** acknowledged this as an issue. :-/

If you recreate your user profile (or create a new user) and try to set the Scheduled Task to run at startup, it will likely work for you.

Also worth noting, if Windows was installed directly from 22H2 install media, the Scheduled Task runs at startup without issue.

**Comment by DesktopECHO** [comment]
Don't use a blank password, the scheduled task will not work without one set.

**Comment by DesktopECHO** [comment]
To deal with Salsa being down, you can change line 25:

`POWERSHELL.EXE -Command "Start-BitsTransfer -Source https://salsa.debian.org/debian/WSL/-/raw/master/x64/install.tar.gz?inline=false -Destination '%TEMP%\%IMG%'" >NUL 2>&1`

To:

`POWERSHELL.EXE -Command "Start-BitsTransfer -Source https://github.com/DesktopECHO/Pi-Hole-for-WSL1/raw/cdf4465044cdfafbc1a0e0098cea5271a217d587/debian11.1b9e7597.tar.gz -Destination '%TEMP%\%IMG%'" >NUL 2>&1`

**Comment by DesktopECHO** [comment]
Getting it to run at automatically at boot is going to be a hassle thanks to this obscure bug.  It only happens with user profiles upgraded from 21H2 to 22H2. 

 If Windows 10 *or* 11 is a clean 22H2 install from media, this problem doesn't appear.  See: [Windows 11 22H2 upgrade breaks "Run whether user is logged on or not" scheduled tasks](https://answers.microsoft.com/en-us/windows/forum/all/windows-11-22h2-upgrade-breaks-run-whether-user-is/3469fd3d-9b89-4d66-b523-501baf57185e) for others with the exact same problem.

Actually, the scheduled task will work if you set the Trigger to run **_At log on_** and in the General tab select **_Run only when user is logged on_**  - I might just make run at login the default moving forward.
