### ISSUE TITLE
hostnames not being resolved

### ISSUE THREAD

**Issue by DkGnjCfEcA** [DesktopECHO/Pi-Hole-for-WSL1#85]
![Screenshot 2023-01-21 142248](https://user-images.githubusercontent.com/93782948/213883648-649acfd7-0ad0-4fa5-9621-229253372922.png)

I have manually assigned hostnames on the router and have also configured conditional forward from pi-hole admin interface, but none of the hostnames are being resolved.

**Comment by DkGnjCfEcA** [comment]
![Screenshot 2023-01-21 142546](https://user-images.githubusercontent.com/93782948/213883788-d81ff060-e066-4d3c-8db8-2d4a78bef953.png)

**Comment by DesktopECHO** [comment]
Sorry no idea... You may want to re-create the issue using a 'real' Pi-hole in a Linux VM or a physical box.  

If you do an `nalookup` of one of these IPs using 192.168.1.0 as the DNS server, do they resolve correctly?

**Comment by DkGnjCfEcA** [comment]
> Sorry no idea... You may want to re-create the issue using a 'real' Pi-hole in a Linux VM or a physical box.
> 
> If you do an `nalookup` of one of these IPs using 192.168.1.0 as the DNS server, do they resolve correctly?

Yes, I just setup a Ubuntu instance on a VM and installed the pihole directly from official repo and everything is working fine, DHCP is still being handled by the router but all the hostnames are being shown correctly in pihole. 

I suspect that disabling the DHCP functionality might be causing this.

**Comment by DesktopECHO** [comment]
Hi, if you still have this running, what is your Pi-hole using as a resolver?  From a CMD.EXE window, run:

`"C:\Program Files\Pi-hole\LxRunOffline.exe" r -n Pi-hole -c "cat /etc/resolv.conf"` 

Perhaps this needs to be changed to `127.0.0.1` so Pi-hole can resolve your internal IPs?

**Comment by DkGnjCfEcA** [comment]
I don't have it running at this time, but it is returning the IPs of the 2 PI-holes I have now setup on Ubuntu VMs and configured at Router level.

# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 192.168.1.13
nameserver 192.168.1.9
nameserver fec0:0:0:ffff::1

**Comment by DesktopECHO** [comment]
Thanks for the update.  It sort-of looks like (but probably isn't) [Top Clients (total) and Top Clients (blocked Only) only showing IP addresses after latest Update](https://discourse.pi-hole.net/t/top-clients-total-and-top-clients-blocked-only-only-showing-ip-addresses-after-latest-update/50013)

I might have suggested to change resolv.conf to 127.0.0.1 but if you've got a solution in place I will just close this issue.  If someone else is searching about a similar problem they can reference this report.

Cheers,
D.
