### ISSUE TITLE
[Kaspersky] Need to turn off antivirus before updating gravity

### ISSUE THREAD

**Issue by LethalAspect** [DesktopECHO/Pi-Hole-for-WSL1#86]
So every time I try to update gravity with my antivirus turned on it fails. Is there any way of updating gravity with my antivirus turned on?

**Comment by DesktopECHO** [comment]
Your AV software should have a place where you can add an exception to the file or folder it thinks is malicious.

**Comment by LethalAspect** [comment]
> Your AV software should have a place where you can add an exception to the file or folder it thinks is malicious.

I tried that, still does not work

**Comment by DesktopECHO** [comment]
That is what works for evertyone else, verify your AV exclusions are correct.

**Comment by LethalAspect** [comment]
> That is what works for evertyone else, verify your AV exclusions are correct.

The one I whitelisted was the Pi-hole installation folder, should I whitelist all of the files there manually or am I missing a couple files not inside of the installation folder?

**Comment by DesktopECHO** [comment]
What is the exact wording of the alert message from your AV?  It should name which process it’s not happy with.  That’s the one you need to exclude.

**Comment by LethalAspect** [comment]
> What is the exact wording of the alert message from your AV? It should name which process it’s not happy with. That’s the one you need to exclude.

Thats the weird thing though, it doesn't prompt anything. It just fails to update gravity when turned on

**Comment by DesktopECHO** [comment]
Unfortunately that’s the info we need to troubleshoot further.  Check support forums for the AV software?  It’s not normal for AV software to silently kill processes on a user’s machine.

**Comment by LethalAspect** [comment]
I checked Firewall, Network Attack Blocker, and System Watcher logs but I still could not find anything

**Comment by DesktopECHO** [comment]
Install better AV software?

**Comment by LethalAspect** [comment]
I have paid and extended over the 30 day refund. Its just a minor inconvenience so I dont mind

**Comment by LethalAspect** [comment]
I will test out a few solutions that I found in the forums to see if they help. Thanks for the help though
