### ISSUE TITLE
DNSCrypt Port

### ISSUE THREAD

**Issue by Kncuk** [DesktopECHO/Pi-Hole-for-WSL1#87]
Hi, I'm curious about using a different port, if I set the listening port on Simple DNSCrypt to say 2345, should that also be the port I set for Pi-hole? My understanding is that port 53 is for DNS so Simple DNSCrypt should be listening on 53 instead, but in #16 you mentioned not to use 53 so I'm not sure what port Simple DNSCrypt should be listening on. On the dash I do get all three green on status so Pi-hole is working, but I'm not certain if all DNS is routed through and getting encrypted. 

As well, if Pi-Hole support DNSCrypt natively how should I go about setting that up? 
Thanks

**Comment by DesktopECHO** [comment]
Unbound is pre-installed, and uses DNS-over-TLS so you don't need SimpleDNScrypt. But if you want to use it instead and it's listening on port 2345 then you'd change the setting below to `127.0.0.1#2345`
 
![image](https://user-images.githubusercontent.com/33142753/221425986-f54cf292-49a9-44f6-8f69-a627b5c9a295.png)

**Comment by Kncuk** [comment]
Thanks you
