### ISSUE TITLE
PiHole installer said it would use port 60800, the lighttpd external.conf file says the port is 60800, but I can only access the Web UI via port 80

### ISSUE THREAD

**Issue by arjunsrinivasan1997** [DesktopECHO/Pi-Hole-for-WSL1#88]
I recently installed pihole and the installer script said that port 60800 would be used. I had no problems with that port being used, but after the install when I tried to go to the web ui at that port the page did not load. I tried using port 80 after some searching and that somehow worked, and I can access the webui from there. However, if I try changing the port in the `Pi-hole\etc\lighttpd/external.conf` file, nothing happens and i still have to go to `IP_ADDRESS:80/admin` to access the webui. Additionally, running `netstat -a -b` in windows command prompt shows nothing listening on port 60080. This isn't a huge issue, as everything still works, but I would like to be able to change the port the pihole runs on.

**Comment by arjunsrinivasan1997** [comment]
I was able to fix it by opening `Pi-hole\etc\lighttpd\lighttpd.conf` and changing the `server.port` value to my desired port. This is a  fix, so if this seems isolated to me feel free to close the issue, but I do think there may be an issue with the install script not properly changing the port of lighttpd during install.

**Comment by DesktopECHO** [comment]
Hi, 

Thanks for the bug report.  Recently, upstream changed the location for setting a custom port in `lighttpd`.  It was:
`/etc/lighttpd/external.conf`  

...But that setting is now here:
`/etc/lighttpd/conf-enabled/07-port.conf`

Moments ago I pushed out an update to account for this change.  

Just a heads-up; the method you used to set the port will be overwritten next time Pi-hole is updated.  Recommend you uninstall and re-install Pi-hole using the updated script.  It tries to use port 80 but if it's in use by another service, port 60080 will be selected instead.  You can set a different port by editing `/etc/lighttpd/conf-enabled/07-port.conf`

**Comment by arjunsrinivasan1997** [comment]
Hey,
Thanks for the info and for the quick fix. I will definitely uninstall and re-install to prevent the overwrite from happening.
