### ISSUE TITLE
Firefox not being monitored

### ISSUE THREAD

**Issue by Kncuk** [DesktopECHO/Pi-Hole-for-WSL1#89]
Hi, it appears that traffic coming from Firefox is not being routed to Pi-hole (and I suspect some other apps too). I have instagram blocked, which cannot be accessed with native Edge browser, but can be with Firefox (set as default). Is there anyway to check all traffic from PC is being routed to Pi-Hole?

Thanks

**Comment by DesktopECHO** [comment]
See: 
https://support.mozilla.org/en-US/kb/firefox-dns-over-https
…to disable use of FireFox’s own DoH servers

**Comment by DesktopECHO** [comment]
[How To Enable/Disable DNS Over HTTPS (DoH) In Firefox?](https://mywindowshub.com/how-to-enable-disable-dns-over-https-doh-in-firefox/)

![image](https://user-images.githubusercontent.com/33142753/222802653-c0b5347f-7c73-4389-9a65-dc4e54ec5149.png)

![image](https://user-images.githubusercontent.com/33142753/222802701-7679de0c-9fb0-45cc-b921-eacba9dd647d.png)

**Comment by Kncuk** [comment]
> See: https://support.mozilla.org/en-US/kb/firefox-dns-over-https …to disable use of FireFox’s own DoH servers

Ah, thanks for the quick response, I did not know DoH interferes.
