### ISSUE TITLE
installed successfully but nothing seems to be blocked

### ISSUE THREAD

**Issue by lorvent** [DesktopECHO/Pi-Hole-for-WSL1#9]
Hello,
after trying many other scripts on windows, i have tried yours (and seems to be most easiest of all)

but after i installed, i don't see any ads being blocked.

do i need to do anything else after installation?

dashboard says 0 total queries and 0 queries blocked

thanks.

---

update: restarted PC and still i don't see any difference.
google ads are being displayed, youtube is showing ads and other sites showing ads aswell.

**Comment by DesktopECHO** [comment]
Hi,

Did you set the DNS server on your PC to point at the Pi-hole DNS server? 
That would be 127.0.0.1 in this case, or your PC's IP address on your LAN if you want other devices to use Pi-hole) 

Regards,
D.

**Comment by lorvent** [comment]
Hello,
i have tried it on same pc, didn't work

then i have tried in my mobile setting DNS1 of IP settings to the pc where i installed it, it was not connecting to internet at all.

I am really not sure if i missed anything but i just followed docs and installed it.

**Comment by DesktopECHO** [comment]
Can you confirm Pi-hole is running at start-up and that you can reach the Pi-Hole web admin page?

**Comment by DesktopECHO** [comment]
Any update? 
When you run "Pi-hole Configuration.cmd" and select repair, does the web page appear after it's complete?

**Comment by lorvent** [comment]
I am sorry for making you wait (and so nice of you for looking into it), i am out on holidays and i will be back in a day and i will update you.

thanks

**Comment by lorvent** [comment]
Hello,
I un-installed it from program files and then i installed it again.

this time, it seems to be working and blocking domains.

but i see that

* google ads are being displayed
* carbon ads are being displayed
* i see ads while playing videos in youtube.

do you think that is normal behavior or i am missing something?

Also, in some screenshots (ex: the screenshot on pi-hole.net website) has more than 123k domains on blocklist and ours has around 58k

https://i0.wp.com/pi-hole.net/wp-content/uploads/2018/12/dashboard.png?zoom=1.75&w=3840&ssl=1

another is, while installing...it is not able to get any malware domains ( i can attach log, if you want)

thanks.

**Comment by DesktopECHO** [comment]
Hi there, I think it's related to this issue:
https://discourse.pi-hole.net/t/malwaredomains-com-down/41770

Go to Group Management -> Ad Lists 
 - Add: https://dbl.oisd.nl/
 - (Or any list you prefer)

Go to Tools -> Update Gravity

Run the Pi-Hole Scheduled task to restart Pi-Hole

This should get you sorted out.

Thanks,
D.

**Comment by lorvent** [comment]
Hello,
I have added lists but still few issues exists

1. it is not started when pc is restarted, so i had run `pi hole launcher.cmd` then admin panel opens up and status says `Active`
2. whenever i access sites from other devices, i don't see logs in admin so i am really not sure whether server is running or not and i see ads on websites.

can you think of any solutions for them?

thanks for your support.

**Comment by lorvent** [comment]
Also, if it helps.... when i run update gravity, it says

```
[i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Using libz compression

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Received 58501 domains

  [i] Target: https://mirror1.malwaredomains.com/files/justdomains
  [✗] Status: Not found
  [✗] List download failed: no cached list available

  [i] Target: https://dbl.oisd.nl/
  [✓] Status: No changes detected
  [i] Received 1075248 domains

  [i] Target: https://someonewhocares.org/hosts/zero/hosts
  [✓] Status: No changes detected
  [i] Received 14597 domains

  [i] Target: https://adaway.org/hosts.txt
  [✓] Status: No changes detected
  [i] Received 9184 domains

  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [i] Number of gravity domains: 1157530 (1092752 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 2
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [✓] Cleaning up stray matter

  [✗] DNS service is NOT listening
```

does it mean pi-hole not running?

**Comment by lorvent** [comment]
Finally, i decided to un-install it and do it again (as it worked last time that way)

after installing again, it is working very fine, i am able to configure directly in router and use it.

but after restarting PC, it is not starting up, i manually had to run `Pi-hole launcher.cmd` to have it running.

Another doubt:
i have ublock origin which effectively blocks ads in youtube and also i don't see any google ads in any website

where as with pi-hole, i still see google ads..... so can't we import all lists from ublock origin into pi-hole?

thanks.

**Comment by DesktopECHO** [comment]
> but after restarting PC, it is not starting up, i manually had to run Pi-hole launcher.cmd to have it running.

Sounds like you don't have the scheduled task set to run at Windows start-up.

> i have ublock origin which effectively blocks ads in youtube and also i don't see any google ads in any website

Check out: https://github.com/nickspaargaren/no-google

**Comment by lorvent** [comment]
Hello,

i have installed it again today in a different PC, first time installed...it doesn't work but with second installation...it works fine.
i guess it is related to a bug which will be shown while installing.

now everything seems to be working fine, except... whenever i restart pc....it is not auto-starting....i had to run `Pi-hole Launcher.cmd` then everything works normal....so probably it is not adding program to scheduler.

can you suggest me, any solution for it?

thanks.

**Comment by lorvent** [comment]
Also, another important thing is....it is using port 80 but i need it to run apache for local development.

so can you tell me where to change port?

thanks.

**Comment by DesktopECHO** [comment]
Do you see "Pi-hole for Windows" in Scheduled Tasks?  
If so, have you set it to start at boot? (As described in the installation instructions)

**Comment by lorvent** [comment]
Hello,
i have it in scheduled tasks and set trigger to "at system startup" but still it doesn't work that way.

so i created a shortcut for "pi-hole launcher.cmd" and put that in `startup` folder so issue is solved :)

**Comment by DesktopECHO** [comment]
Open Windows Task Scheduler (taskschd.msc)

- Right-click the task named **Pi-hole for Windows** and click edit.
- On the **General** tab, place a checkmark next to:
         - **Run whether user is logged on or not**
         - **Run with highest privileges**
         - **Hidden**
![image](https://user-images.githubusercontent.com/33142753/106790998-bb2ed400-662a-11eb-9ddd-65ff5e9f3297.png)
- On the Conditions tab, un-check the option **Start the task only if the computer is on AC power**

If that doesn't work you may need to re-create the scheduled task.  Sounds like you have a workaround in place so we won't spend anymore time on this issue.

Thanks,
D.
