### ISSUE TITLE
Failed to Mount

### ISSUE THREAD

**Issue by DelrinGibs** [DesktopECHO/Pi-Hole-for-WSL1#91]
I am new to playing around with this kind of stuff so I'm hoping it is an easy answer. I am running windows 11. Ran the PH4WSL1 and it would download things but always come back with multiple messages stating an error occurred mounting one of your file systems. When install was finished it prompted me to hit any button and it would open a blank page that should have been my dashboard. 

I found some advice suggesting I update running the command wsl -update. I ran this and it did update successfully, but now I get a failed to mount and it never even gets to attempting to install.

--------------------------------
 Pi-hole for Windows v.20230301
--------------------------------

Set Pi-hole install location, or hit enter for default [C:\Program Files] ->
Processing fstab with mount -a failed.
Failed to mount A:\, see dmesg for more details.
Failed to mount C:\, see dmesg for more details.
Failed to mount D:\, see dmesg for more details.
Failed to mount G:\, see dmesg for more details.

<3>WSL (9) ERROR: CreateProcessEntryCommon:368: getpwuid(0) failed 2
<3>WSL (9) ERROR: CreateProcessEntryCommon:372: getpwuid(0) failed 2
<3>WSL (9) ERROR: CreateProcessEntryCommon:574: execvpe . failed 13
<3>WSL (9) ERROR: CreateProcessEntryCommon:583: Create process not expected to return

Existing Pi-hole installation detected, uninstall Pi-hole first.
Press any key to continue . . .

**Comment by DesktopECHO** [comment]
Yeah as you've already seen online there's a dodgy WSL update somewhere along the line that caused this.
If you updated WSL so you should be ok now.  

> Existing Pi-hole installation detected, uninstall Pi-hole first.
Press any key to continue . . .

This tells us it needs to clean up a failed install - Run the uninstaller:  

`C:\Program Files\Pi-hole\Pi-hole Uninstall.cmd`

After uninstall, if that folder is not empty, reboot and manually delete it.  Set the WSL1 default to 1 to make sure there are no more issues: (You can switch the default back to WSL2 after the Pi-hole install if you want)

`wsl --set-default-version 1`

Now you can run `PH4WSL1.CMD` and the install should proceed normally.

**Comment by DelrinGibs** [comment]
Thank you, with your guidance and  a little bit of realizing I'm dumb its fixed and working. Before I updated WSL the first time I stupidly did not delete the current pi-hole install correctly, I only deleted the folder in the C drive. Had to go in and fully delete it, for safety I reinstalled WSL and re-updated it then set to version 1. Thank you so much.
