### ISSUE TITLE
Easy switch to Cloudflare?

### ISSUE THREAD

**Issue by seanbperiod** [DesktopECHO/Pi-Hole-for-WSL1#92]
Hello 👋

I'm interested in switching over to cloudflare as the DNS, and just want to double check that I'm doing it correctly. 

Do I just switch the upstream server from OpenDNS to Cloudflare and save? 

I initially found this [article](https://nathancatania.com/posts/pihole-dns-doh/ ) about it and was pleasantly surprised to see that doH was already incorporated here, but not sure if I should mirror the settings as shown below. 

I appreciate the help. Thanks! 

From article: 
![image](https://user-images.githubusercontent.com/8443498/225738147-d91d56a7-0f08-4152-9f8a-94120623c0af.png)

My current settings: 
<img width="504" alt="Screenshot 2023-03-16 at 3 56 49 PM" src="https://user-images.githubusercontent.com/8443498/225738501-c4ec78da-906c-433b-8dd9-46bfebc77a2d.png">

**Comment by DesktopECHO** [comment]
Hi, I think this is what you're looking for... from a PowerShell Window:

`& 'C:\Program Files\Pi-hole\LxRunOffline.exe' r -n Pi-hole -c "nano /etc/unbound/unbound.conf.d/pi-hole.conf"`

![image](https://user-images.githubusercontent.com/33142753/225914130-a2ae865f-a0a7-4835-9a67-bf0e9553808e.png)

Out-of-the-box, default is to use Cloudflare and Quad9 in round-robin.

**Comment by DesktopECHO** [comment]
Where is it using OpenDNS?  
It’s already set-up to use Cloudflare and Quad9 in round-robin.

**Comment by seanbperiod** [comment]
From the upstream settings. OpenDNS is checked.

**Comment by DesktopECHO** [comment]
Those checkboxes for OpenDNS must have been added after the install was completed. 

By default, the only upstream DNS server is `127.0.0.1#5335`, which is the Unbound DNS server.  Unbound then makes the external DNS-over-TLS request using Quad9 or CloudFlare and relays the response back to the Pi-hole.
