### ISSUE TITLE
Do I need to update every time you make a change to the program?

### ISSUE THREAD

**Issue by LethalAspect** [DesktopECHO/Pi-Hole-for-WSL1#94]
im just wondering if i should update since you changed something with the program

**Comment by DesktopECHO** [comment]
No need to re-run PH4WSL1.CMD at this time.  Most of the changes done were to make the initial install faster and more reliable.
 
When upstream publishes an update to Pi-hole, you can run ```C:\Program Files\Pi-hole\Pi-hole System Update.cmd``` to get the latest update installed.

**Comment by LethalAspect** [comment]
> No need to re-run PH4WSL1.CMD at this time. Most of the changes done were to make the initial install faster and more reliable.
> 
> When upstream publishes an update to Pi-hole, you can run `C:\Program Files\Pi-hole\Pi-hole System Update.cmd` to get the latest update installed.

I already know how to update Pi-Hole but thanks!
