### ISSUE TITLE
WireGuard server can't start using systemctl

### ISSUE THREAD

**Issue by gingercookies** [DesktopECHO/Pi-Hole-for-WSL1#97]
Hi, recently i tried out your script and now i want to install wireguard server to redirect my phone to pihole (when using mobile network). 
I install wireguard, wireguard-tools, wireguard-dkms and systemctl through terminal using: wsl -d Pi-hole
After fully config wireguard with the guide come from [this](https://docs.pi-hole.net/guides/vpn/wireguard/server/)
I tried to register through commands:
- sudo systemctl enable wg-quick@wg0.service
- sudo systemctl start wg-quick@wg0

But both of them output the same thing: 
 ERROR:systemctl:Unit wg-quick@wg0.service could not be found.

**Comment by DesktopECHO** [comment]
Hi, you need to deploy a separate WSL2 VM to set up Wireguard as Pi-hole is intended to run on WSL1.

**Comment by gingercookies** [comment]
So wireguard can't be run on the same wsl as pi-hole?

**Comment by DesktopECHO** [comment]
You can try converting it to WSL2, but at that point you're probably better just better off jumping into container technology like Docker.  There is some learning overhead, but totally worth it.

**Comment by gingercookies** [comment]
Ok, i will try it later.
Thanks for helping me
