### ISSUE TITLE
No data showing

### ISSUE THREAD

**Issue by VOGUK** [DesktopECHO/Pi-Hole-for-WSL1#98]
Pi-hole is running and blocking all ads. However, it doesn't show any data on the control panel, i.e. number or active clients, blocked queries and all queries. What can I do to rectify this?

**Comment by DesktopECHO** [comment]
Try running:

`C:\Program Files\Pi-hole\Pi-hole Configuration.cmd`

And select **Repair**

![image](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/assets/33142753/965d4f08-7485-4181-ac83-867efe17ef8b)

**Comment by VOGUK** [comment]
No, that doesn't work. I tried flushing the logs and restarting the system too.

**Comment by DesktopECHO** [comment]
After running "Repair" can you send a screenshot of the browser window that is opened automatically?

Also can you try accessing it from http://127.0.0.1/admin ?

**Comment by VOGUK** [comment]
Sure, here you go. 
![ss](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/assets/106017730/586aa918-6f65-436e-9159-3970306ff0f9)

**Comment by DesktopECHO** [comment]
That's strange... open a command prompt and run:

`````nslookup.exe github.com 127.0.0.1`````

You shoudl see something like this in response:
`````
Server:  localhost
Address:  127.0.0.1

Non-authoritative answer:
Name:    github.com
Address:  140.82.112.4
`````

Does the query show up in the quwery log?

`````http://localhost/admin/queries.php`````

![image](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/assets/33142753/7fe2ae87-dbbb-4f63-9ebe-54c584fd9f59)

**Comment by VOGUK** [comment]
Hi, I don't know if you meant the address to start 127... or 117... so I did both. There were no queries being shown and there was also a notification showing which I have added the screenshot of below too. 

![ss](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/assets/106017730/9d4ab4a2-10fa-410a-8b3f-40ab10dbcf6e)
![ss2](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/assets/106017730/932621ca-57d3-4b3d-9156-0ea09a739d
![ss3](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/assets/106017730/267db0e6-9caf-4754-a223-a86153014f5f)
d9)

**Comment by VOGUK** [comment]
For some reason the second screenshot didn't load, please find it below. 
![ss2](https://github.com/DesktopECHO/Pi-Hole-for-WSL1/assets/106017730/af7022ea-02b2-4ec6-9d10-8c7b9156d7d5)
