### ISSUE TITLE
tzdata requires manual configuration with no prompt

### ISSUE THREAD

**Issue by unwovened** [DesktopECHO/Pi-Hole-for-WSL1#99]
When attempting to install the newest version of PH4WSL, the prompt stops at 
`Please wait a few minutes for package installer . . . `
with no additional information to the user. From the install-log, it shows this is due to tzdata prompting the user to chose a timezone location. Pressing "Enter" twice blindly at the prompt addresses the issue, but does not correctly set tzdata.
Recommendation: Pre-seed tzdata configuration based on local system settings.

**Comment by DesktopECHO** [comment]
Looks like the install.tar.gz from salsa.debian.org went from version 11 to 12 recently.  

I tweaked the script so it links back to Debian 11 - Now the installer completes without issue.

Thank you for the report!
